import type { Dictionary } from "./types";

export const en: Dictionary = {
  meta: {
    title: "TechHala — AI robots for learning English & the family",
    description:
      "TechHala AI robots help students practise spoken English every day, and act as AI assistants for Vietnamese families. Priced from 2 to 4 million VND, nationwide delivery, cash on delivery. Hotline (+84) 0868 862 564.",
    ogTitle: "TechHala — AI robots for students & families, from 2M VND",
  },
  nav: {
    products: "Products",
    solutions: "Solutions",
    work: "Work",
    about: "About",
    contact: "Contact",
    shopNow: "Shop now",
    menu: "Menu",
    close: "Close",
  },
  common: {
    learnMore: "Learn more",
    viewAll: "View all",
    back: "Back",
    talkToUs: "Talk to us",
    industry: "Industry",
    challenge: "Challenge",
    solution: "Solution",
    results: "Results",
    relatedSolution: "Related solution",
    theme: "Toggle theme",
    language: "Language",
  },
  shop: {
    priceFrom: "From",
    buyNow: "Buy now",
    addToOrder: "Order",
    viewDetails: "View details",
    contactUs: "Ask for advice",
    callUs: "Call us",
    zalo: "Chat on Zalo",
    email: "Email",
    address: "Address",
    phone: "Hotline",
    categories: {
      education: {
        name: "English-learning AI robots",
        short: "A speaking partner for students aged 4 – 15, every day.",
      },
      home: {
        name: "AI robots for the home",
        short: "Family assistants: reminders, conversation, calls, elderly care.",
      },
      combo: {
        name: "Value bundles",
        short: "Bundles for siblings and the whole family — save up to 400,000đ.",
      },
      accessory: {
        name: "Accessories & content",
        short: "Charging dock, protective case, flashcards and the Premium content plan.",
      },
    },
    ages: {
      "4-8": { name: "Ages 4 – 8", short: "Preschool, grades 1 – 3 · first English through songs and stories" },
      "6-12": { name: "Ages 6 – 12", short: "Primary · speaking practice tied to class, Cambridge Starters – Flyers" },
      "9-15": { name: "Ages 9 – 15", short: "Lower secondary · KET/PET prep, presentations, writing" },
      family: { name: "Whole family", short: "Living-room assistant · reminders, video calls, smart home" },
      seniors: { name: "Grandparents", short: "Medication reminders, news, conversation, calling the family" },
    },
    labels: {
      audience: "Made for",
      highlights: "Highlights",
      features: "Features",
      specs: "Specifications",
      inBox: "What's in the box",
      video: "Product video",
      gallery: "Product photos",
      related: "Other products",
      allProducts: "All products",
      priceNote: "Prices include VAT · Free nationwide delivery · 12-month warranty",
      freeShipping: "Free shipping",
      sold: "sold",
      reviews: "reviews",
      save: "Save",
      color: "Color",
      age: "Age",
      inStock: "In stock · Delivered in 2 – 4 days",
      lowStock: "Only {n} left · Delivered in 2 – 4 days",
      outOfStock: "Out of stock",
      outOfStockHint: "This colour is temporarily out of stock. Pick another colour or call/Zalo us to pre-order.",
      filterAll: "All",
      filterCategory: "Category",
      filterAge: "Age",
      filterPrice: "Price",
      sortBy: "Sort",
      sortOptions: [
        { id: "popular", label: "Best selling" },
        { id: "price-asc", label: "Price: low → high" },
        { id: "price-desc", label: "Price: high → low" },
        { id: "rating", label: "Top rated" },
      ],
      result: "product",
      results: "products",
      noResults: "No products match these filters. Try removing one.",
      clearFilters: "Clear filters",
      priceRanges: [
        { id: "under-1m", label: "Under 1Mđ", min: 0, max: 1000000 },
        { id: "2m-3m", label: "2 – 3Mđ", min: 2000000, max: 3000000 },
        { id: "3m-4m", label: "3 – 4Mđ", min: 3000000, max: 4000000 },
        { id: "over-4m", label: "Over 4Mđ (bundles)", min: 4000000 },
      ],
    },
    cart: {
      title: "Your cart",
      open: "Open cart",
      close: "Close cart",
      empty: "Your cart is empty.",
      emptyCta: "Browse products",
      addToCart: "Add to cart",
      added: "Added to cart",
      remove: "Remove",
      subtotal: "Subtotal",
      shippingFree: "Free nationwide delivery",
      checkout: "Checkout",
      continueShopping: "Continue shopping",
      items: "items",
      quantity: "Quantity",
    },
    guarantees: [
      { title: "12-month warranty", body: "Replacement within the first 30 days for manufacturer defects." },
      { title: "Nationwide delivery", body: "Free shipping across Vietnam, delivered in 2 – 4 business days." },
      { title: "Flexible payment", body: "Cash on delivery (COD) or bank transfer." },
      { title: "Friendly support", body: "Hotline & Zalo support for setup, parents, and students." },
    ],
  },
  home: {
    hero: {
      eyebrow: "TechHala AI robots",
      title: "An English buddy",
      highlight: "that listens.",
      subtitle:
        "AI robots that help kids practise spoken English every day like talking to a real friend — correcting pronunciation, telling stories, playing vocabulary games. Plus assistant robots for the whole family: reminders, conversation with grandparents, staying connected.",
      primaryCta: "See products",
      secondaryCta: "Call for advice",
      bullets: ["2 – 4 million VND", "Nationwide delivery", "Cash on delivery", "12-month warranty"],
      priceBadge: "From",
    },
    strip: ["Free nationwide shipping", "Cash on delivery", "12-month warranty · 30-day replacement", "Hotline (+84) 0868 862 564"],
    stats: [
      { value: "5,000+", label: "families" },
      { value: "4.8/5", label: "parent rating" },
      { value: "2 – 4Mđ", label: "robot prices" },
      { value: "12 mo", label: "warranty" },
    ],
    bubbles: { robot: "Hi! What did you eat for lunch today? 🍜", child: "I ate… phở! It was yummy!" },
    ages: {
      eyebrow: "Shop by age",
      title: "How old is your child?",
      subtitle: "Each age group has a robot matched to its level and way of learning. Pick one to see our suggestions.",
    },
    categories: {
      eyebrow: "Categories",
      title: "Pick the robot that fits your family",
      subtitle: "Two product lines, one conversational AI developed and continuously updated by TechHala.",
    },
    catalog: {
      eyebrow: "Best sellers",
      title: "The robots parents pick most",
      subtitle: "Every product has a listed price — order directly on the website or call the hotline for advice.",
    },
    bundles: {
      eyebrow: "Bundles & accessories",
      title: "Buy as a set, save more",
      subtitle: "Bundles for siblings and the whole family, plus genuine accessories: dock, case, flashcards, Premium plan.",
    },
    testimonials: {
      eyebrow: "What parents say",
      title: "Trusted by 5,000+ families",
      items: [
        {
          quote: "My 6-year-old used to be shy about speaking English. Three weeks with HalaBuddy Mini and she asks to ‘chat with robot’ every night before bed.",
          name: "Minh Anh",
          role: "Mum of Bông, Hanoi",
        },
        {
          quote: "His speaking score went up noticeably and his teacher praised his pronunciation. I love the weekly report — I finally know what he's practising.",
          name: "Quoc Huy",
          role: "Dad of Nam, grade 5, HCMC",
        },
        {
          quote: "We bought HalaCare for grandma back home. She takes her medicine on time and calls us with a single sentence. The whole family feels reassured.",
          name: "Thu Ha",
          role: "Da Nang",
        },
      ],
    },
    why: {
      eyebrow: "Why TechHala",
      title: "Built by TechHala — not a pre-programmed toy",
      subtitle:
        "The intelligence inside each robot is the same conversational AI TechHala deploys for enterprises, tuned for Vietnamese children and families.",
      items: [
        {
          title: "Natural conversation with correction",
          body: "The robot understands a child's half-formed sentences, replies naturally, and gently corrects pronunciation and grammar mid-conversation.",
        },
        {
          title: "Aligned with the curriculum",
          body: "Content follows the Vietnamese primary and lower-secondary English curriculum plus Cambridge Starters/Movers/Flyers, KET, and PET.",
        },
        {
          title: "Parents see the progress",
          body: "Weekly reports in the app: speaking time, new words, frequent pronunciation errors, and tips for parents.",
        },
        {
          title: "Safe for children",
          body: "Age-filtered content, no ads, no social media. Voice data is protected and can be deleted at any time.",
        },
        {
          title: "Speaks Vietnamese too",
          body: "The robot explains in Vietnamese when a child is stuck, then encourages them back into English.",
        },
        {
          title: "Always improving",
          body: "New lessons, games, and voices arrive automatically over Wi‑Fi — the robot keeps getting smarter.",
        },
      ],
    },
    steps: {
      eyebrow: "Simple to buy",
      title: "From order to the first lesson",
      subtitle: "Four steps, no technical knowledge needed.",
      items: [
        { name: "Choose a robot", desc: "Pick by age and need, or call the hotline for a recommendation." },
        { name: "Place the order", desc: "Enter delivery details and choose cash on delivery or bank transfer." },
        { name: "Receive it", desc: "Delivered to your door in 2 – 4 business days; inspect before paying." },
        { name: "Start learning", desc: "Connect Wi‑Fi, create your child's profile in 5 minutes, and start the first conversation." },
      ],
    },
    family: {
      eyebrow: "AI robots for the home",
      title: "Not just for kids — an assistant for the whole family",
      body:
        "The HalaHome and HalaCare line brings conversational AI into the living room: school and medication reminders, weather and news, video calls to relatives, and company for grandparents while everyone is at work.",
      bullets: [
        "Reminders, medication alerts, and alarms in a natural voice",
        "Call a family member with a single sentence",
        "Conversation, news, stories, and music for the elderly",
        "Control compatible lights, fans, and TVs",
      ],
      cta: "See home robots",
    },
    faq: {
      title: "Frequently asked questions",
      items: [
        {
          q: "Does the robot need an internet connection?",
          a: "Yes. It uses your home Wi‑Fi for conversation and lesson updates. Some games and songs still work offline.",
        },
        {
          q: "My child is 5 and can't read yet — can they use it?",
          a: "Yes. HalaBuddy Mini is designed for ages 4 – 8 and works entirely by voice, no reading required.",
        },
        {
          q: "Is there a monthly fee?",
          a: "No. The purchase price includes the core lessons and software updates with no mandatory subscription. The optional Premium pack adds extra lessons and exam prep.",
        },
        {
          q: "How do I pay?",
          a: "Cash on delivery anywhere in Vietnam, or bank transfer after our team confirms your order.",
        },
        {
          q: "What about warranty?",
          a: "12-month warranty, replacement within 30 days for manufacturer defects. Technical support via hotline and Zalo.",
        },
        {
          q: "Bulk orders for schools or centres?",
          a: "We offer special pricing and classroom management accounts for schools and English centres. Call the hotline for a quote.",
        },
      ],
    },
    solutions: {
      eyebrow: "For businesses",
      title: "TechHala also builds AI for software teams and enterprises",
      body:
        "The AI behind our robots is also deployed for enterprise clients: the HAL‑SDLC platform for AI-driven software development, internal chatbots & AI assistants, and AI operations (AIOps).",
      cta: "See enterprise solutions",
    },
    cta: {
      title: "Not sure which robot is right for your child?",
      body: "Call or message us on Zalo — the TechHala team will recommend one based on age, level, and learning goals in 10 minutes.",
      primary: "Call (+84) 0868 862 564",
      secondary: "Request advice",
    },
  },
  products: {
    title: "AI robot products",
    subtitle:
      "English-learning AI robots for students and AI home assistants developed by TechHala. Listed prices 2 – 4 million VND, nationwide delivery.",
    items: [
      {
        slug: "halabuddy-mini",
        name: "HalaBuddy Mini",
        category: "education",
        art: "mini",
        tint: "pink",
        tagline: "English-learning robot for ages 4 – 8",
        price: 2290000,
        compareAtPrice: 2590000,
        rating: 4.8,
        sold: 1240,
        freeShipping: true,
        ages: ["4-8"],
        ageLabel: "Ages 4 – 8",
        colors: [
          { id: "pink", name: "Pink", hex: "#ff8fa3" },
          { id: "mint", name: "Mint", hex: "#7fd8c8" },
          { id: "yellow", name: "Yellow", hex: "#ffd166" },
        ],
        badge: "For beginners",
        audience: "Children aged 4 – 8, preschool to grade 3",
        summary:
          "A compact, voice-only learning buddy. Kids meet English through songs, stories, word-guessing games, and short cheerful conversations every day.",
        highlights: [
          "300+ songs, stories, and vocabulary games",
          "Recognises children's voices, responds gently",
          "No screen — easy on young eyes",
          "Parent-set daily time limits",
        ],
        features: [
          { title: "Topic conversations", body: "Colours, animals, family, food… one topic a day, 10 – 15 minutes per session." },
          { title: "Songs and stories", body: "An age-graded library of English songs and stories, with slow versions to repeat along." },
          { title: "Rewards and badges", body: "Kids earn badges for learning streaks; parents see them in the app." },
          { title: "Bilingual mode", body: "Explains in Vietnamese when needed, then returns to English." },
        ],
        specs: [
          { label: "Size", value: "14 × 10 × 10 cm · 420 g" },
          { label: "Battery", value: "6 – 8 hours, USB‑C charging" },
          { label: "Connectivity", value: "Wi‑Fi 2.4 GHz, Bluetooth 5.0" },
          { label: "Audio", value: "3 W speaker, 2 noise-cancelling mics" },
          { label: "App", value: "TechHala Parent (iOS/Android)" },
        ],
        inBox: ["HalaBuddy Mini robot", "USB‑C cable", "Bilingual quick-start guide", "50 vocabulary flashcards"],
      },
      {
        slug: "halabuddy",
        name: "HalaBuddy",
        category: "education",
        art: "buddy",
        tint: "yellow",
        tagline: "Speaking partner for primary and lower-secondary students",
        price: 2990000,
        compareAtPrice: 3490000,
        rating: 4.9,
        sold: 3120,
        freeShipping: true,
        ages: ["6-12", "9-15"],
        ageLabel: "Ages 6 – 15",
        colors: [
          { id: "white", name: "White", hex: "#f4f4f4" },
          { id: "red", name: "TechHala Red", hex: "#e60012" },
          { id: "blue", name: "Blue", hex: "#4f8ef7" },
        ],
        badge: "Best seller",
        audience: "Students aged 6 – 15, grades 1 – 9",
        summary:
          "A full conversational robot: speaking practice aligned with the school curriculum, sentence-level pronunciation scoring, vocabulary review by lesson, and weekly progress reports for parents.",
        highlights: [
          "Speaking practice for the school curriculum and Cambridge YLE",
          "Sentence-level pronunciation scoring with fixes",
          "Vocabulary review matched to classroom lessons",
          "Weekly progress reports for parents",
        ],
        features: [
          { title: "Situational dialogues", body: "Shopping, introducing yourself, talking about holidays… 500+ scenarios by level." },
          { title: "Detailed pronunciation scoring", body: "Scores per sound, word, and sentence; the robot models the phrase and asks the child to try again." },
          { title: "Synced with class lessons", body: "Choose the textbook series in use (Global Success, Family & Friends, i‑Learn Smart Start…) and the robot reviews the right unit." },
          { title: "Cambridge exam practice", body: "Starters, Movers, and Flyers Speaking practice with instant feedback." },
          { title: "Parent app", body: "See study time, new words, common errors; schedule sessions and set limits." },
        ],
        specs: [
          { label: "Size", value: "18 × 12 × 12 cm · 650 g" },
          { label: "Battery", value: "8 – 10 hours, USB‑C charging" },
          { label: "Connectivity", value: "Wi‑Fi 2.4/5 GHz, Bluetooth 5.0" },
          { label: "Audio", value: "5 W speaker, 4 directional mics" },
          { label: "Display", value: "Expressive LED face" },
          { label: "App", value: "TechHala Parent (iOS/Android)" },
        ],
        inBox: ["HalaBuddy robot", "Charging dock & USB‑C cable", "Bilingual quick-start guide", "100 scenario cards"],
      },
      {
        slug: "halabuddy-pro",
        name: "HalaBuddy Pro",
        category: "education",
        art: "pro",
        tint: "blue",
        tagline: "English tutor robot with screen & camera",
        price: 3990000,
        compareAtPrice: 4490000,
        rating: 4.9,
        sold: 860,
        freeShipping: true,
        ages: ["9-15"],
        ageLabel: "Ages 9 – 15",
        colors: [
          { id: "white", name: "White", hex: "#f4f4f4" },
          { id: "black", name: "Black", hex: "#1a1a1a" },
        ],
        badge: "Premium",
        audience: "Students aged 9 – 15 preparing for KET/PET and IELTS Junior",
        summary:
          "The premium model with a 5-inch touchscreen and camera: learn from images, practise presentations, and get writing and speaking graded against international exam standards.",
        highlights: [
          "5\" touchscreen, camera recognises books and cards",
          "KET, PET, IELTS Junior — Speaking & Writing practice",
          "Presentation practice with recording and feedback",
          "Profiles for up to 3 students per family",
        ],
        features: [
          { title: "Learn from images", body: "Hold a book or object up to the camera — the robot names it, builds sentences, and quizzes your child in English." },
          { title: "Standards-based Speaking", body: "Simulates KET/PET/IELTS Junior speaking tests, scored on pronunciation, vocabulary, grammar, and fluency." },
          { title: "Writing feedback", body: "Photograph handwritten work — the robot reads it, corrects errors, and suggests stronger phrasing." },
          { title: "Presentation coach", body: "Records presentations and comments on pace, intonation, and body language." },
          { title: "Multiple profiles", body: "Up to 3 student profiles, each with its own learning path and reports." },
        ],
        specs: [
          { label: "Size", value: "22 × 14 × 14 cm · 900 g" },
          { label: "Display", value: "5\" IPS touchscreen" },
          { label: "Camera", value: "8 MP with physical privacy cover" },
          { label: "Battery", value: "8 hours, 20 W USB‑C charging" },
          { label: "Connectivity", value: "Wi‑Fi 2.4/5 GHz, Bluetooth 5.2" },
          { label: "Audio", value: "2 × 5 W speakers, 4 directional mics" },
        ],
        inBox: ["HalaBuddy Pro robot", "Charging dock & 20 W adapter", "Bilingual quick-start guide", "120 picture cards", "Carry pouch"],
      },
      {
        slug: "halahome",
        name: "HalaHome",
        category: "home",
        art: "home",
        tint: "green",
        tagline: "AI assistant for the whole family",
        price: 3490000,
        rating: 4.7,
        sold: 540,
        freeShipping: true,
        ages: ["family"],
        ageLabel: "Whole family",
        badge: "New",
        audience: "Families with young children and elderly members",
        summary:
          "A living-room assistant robot: family reminders, weather and news, alarms, video calls to relatives, control of compatible devices, and conversation in both Vietnamese and English.",
        highlights: [
          "Reminders for every family member",
          "Voice-initiated video calls to relatives",
          "Controls compatible lights, fans, and TVs",
          "Bilingual Vietnamese – English conversation",
        ],
        features: [
          { title: "Family calendar", body: "Kids' classes, grandparents' check-ups, parents' meetings — the robot reminds the right person at the right time." },
          { title: "One-sentence video calls", body: "\"Call mum\" — the screen turns to the speaker and connects through the TechHala app." },
          { title: "Smart home", body: "Controls lights, fans, TVs, and compatible smart devices in Vietnamese." },
          { title: "Kids mode", body: "When a child is using it, the robot switches to HalaBuddy-style English learning content." },
        ],
        specs: [
          { label: "Size", value: "24 × 16 × 16 cm · 1.1 kg" },
          { label: "Display", value: "7\" IPS touchscreen, rotates 180°" },
          { label: "Camera", value: "5 MP with physical privacy cover" },
          { label: "Power", value: "12 V adapter, 2-hour backup battery" },
          { label: "Connectivity", value: "Wi‑Fi 2.4/5 GHz, Bluetooth 5.2, infrared" },
          { label: "Audio", value: "2 × 8 W speakers, 6 mics" },
        ],
        inBox: ["HalaHome robot", "12 V adapter", "Quick-start guide", "Setup card"],
      },
      {
        slug: "halacare",
        name: "HalaCare",
        category: "home",
        art: "care",
        tint: "purple",
        tagline: "Companion robot for grandparents",
        price: 2690000,
        compareAtPrice: 2990000,
        rating: 4.8,
        sold: 910,
        freeShipping: true,
        ages: ["seniors"],
        ageLabel: "Grandparents",
        badge: "For seniors",
        audience: "Elderly people living alone or home during the day",
        summary:
          "Compact, with large buttons and a clear voice: medication reminders, news, stories, music, quick calls to family, and all-day conversation in Vietnamese.",
        highlights: [
          "Scheduled medication reminders with confirmation",
          "Call family with one button or one sentence",
          "News, stories, music, and radio",
          "Family app to follow the day's activity",
        ],
        features: [
          { title: "Smart medication reminders", body: "Reminds on time, asks whether the dose was taken, and notifies family if it was missed." },
          { title: "Stay connected", body: "Voice/video calls to saved numbers and voice messages from the TechHala app." },
          { title: "Friendly conversation", body: "Natural, patient Vietnamese voice that checks in and suggests light daily exercise." },
          { title: "Radically simple", body: "Three large buttons, loud volume, no touchscreen required." },
        ],
        specs: [
          { label: "Size", value: "16 × 12 × 12 cm · 600 g" },
          { label: "Battery", value: "12 hours, dock charging" },
          { label: "Connectivity", value: "Wi‑Fi 2.4 GHz, Bluetooth 5.0" },
          { label: "Audio", value: "Loud 5 W speaker, 2 mics" },
          { label: "App", value: "TechHala Family (iOS/Android)" },
        ],
        inBox: ["HalaCare robot", "Charging dock", "Large-print guide", "Setup card"],
      },
      {
        slug: "combo-anh-em",
        name: "Siblings Bundle — 2 × HalaBuddy Mini",
        category: "combo",
        art: "combo-siblings",
        tint: "peach",
        tagline: "Two kids learning together, two robots playing together",
        price: 4290000,
        compareAtPrice: 4580000,
        rating: 4.9,
        sold: 210,
        freeShipping: true,
        ages: ["4-8"],
        ageLabel: "Ages 4 – 8",
        badge: "Save 290K",
        audience: "Families with two children aged 4 – 8",
        summary:
          "Two HalaBuddy Mini robots (pick your colors) that connect to each other: the kids play word quizzes, sing call-and-response songs and role-play dialogues. Separate profiles and reports for each child.",
        highlights: ["2 HalaBuddy Mini robots, choose colors", "Duo mode: word quizzes, sing-alongs", "2 separate student profiles", "2 free 50-card flashcard sets"],
        features: [
          { title: "Duo play", body: "The robots find each other over Wi‑Fi and open two-player word games and role-play dialogues." },
          { title: "Separate profiles", body: "Each child gets their own path, badges and reports in the same parent app." },
        ],
        specs: [
          { label: "Includes", value: "2 × HalaBuddy Mini" },
          { label: "Colors", value: "Choose at checkout (order note)" },
          { label: "Warranty", value: "12 months / robot" },
        ],
        inBox: ["2 HalaBuddy Mini robots", "2 USB‑C cables", "2 × 50-card flashcard sets", "Guide"],
      },
      {
        slug: "combo-hoc-tap",
        name: "Study Bundle — HalaBuddy + Dock + 200 cards",
        category: "combo",
        art: "combo-study",
        tint: "yellow",
        tagline: "The complete kit for primary and lower-secondary students",
        price: 3290000,
        compareAtPrice: 3428000,
        rating: 4.9,
        sold: 480,
        freeShipping: true,
        ages: ["6-12", "9-15"],
        ageLabel: "Ages 6 – 15",
        badge: "Popular bundle",
        audience: "Students aged 6 – 15 who want a daily routine",
        summary:
          "The HalaBuddy robot with a desk dock so it's always charged and ready, plus 200 themed flashcards — the robot recognises each card from your child's reading.",
        highlights: ["Full HalaBuddy", "Desk charging dock", "200 flashcards, 12 topics", "Cheaper than buying separately"],
        features: [
          { title: "Always ready", body: "The dock keeps the robot charged on the desk — just say “Hey Hala” to start." },
          { title: "Learn with cards", body: "Your child reads the word on the card; the robot scores pronunciation and gives an example sentence." },
        ],
        specs: [
          { label: "Includes", value: "HalaBuddy + Dock + 200-card set" },
          { label: "Robot color", value: "White / Red / Blue (order note)" },
        ],
        inBox: ["HalaBuddy robot", "Desk dock", "200 flashcards", "Guide"],
      },
      {
        slug: "combo-gia-dinh",
        name: "Family Bundle — HalaHome + HalaCare",
        category: "combo",
        art: "combo-family",
        tint: "green",
        tagline: "Living-room assistant + a companion for grandparents",
        price: 5790000,
        compareAtPrice: 6180000,
        rating: 4.8,
        sold: 120,
        freeShipping: true,
        ages: ["family", "seniors"],
        ageLabel: "Whole household",
        badge: "Save 390K",
        audience: "Multi-generation households",
        summary:
          "HalaHome in the living room, HalaCare in grandma's room — the two robots share medication schedules, call each other room-to-room and alert the family when needed.",
        highlights: ["HalaHome + HalaCare", "Room-to-room intercom", "Shared family calendar", "Save 390,000đ"],
        features: [
          { title: "Intercom", body: "Say “Call grandma” from the living room — HalaCare rings right in her room." },
          { title: "One app", body: "Both robots are managed from the TechHala Family app." },
        ],
        specs: [{ label: "Includes", value: "HalaHome + HalaCare" }],
        inBox: ["HalaHome robot + adapter", "HalaCare robot + dock", "Guide"],
      },
      {
        slug: "de-sac-halabuddy",
        name: "HalaBuddy desk charging dock",
        category: "accessory",
        art: "dock",
        tint: "blue",
        tagline: "Fast charging, tidy desk",
        price: 290000,
        rating: 4.7,
        sold: 1560,
        freeShipping: true,
        ages: [],
        audience: "For HalaBuddy Mini, HalaBuddy, HalaBuddy Pro",
        summary: "Contact charging dock — just set the robot down. Battery indicator, anti-slip base, 1.5 m USB‑C cable.",
        highlights: ["Contact charging, no cable fiddling", "Battery indicator", "Anti-slip base"],
        features: [{ title: "Compatibility", body: "The whole HalaBuddy line (Mini, standard, Pro)." }],
        specs: [
          { label: "Power", value: "15 W" },
          { label: "Cable", value: "USB‑C 1.5 m" },
        ],
        inBox: ["Charging dock", "USB‑C cable"],
      },
      {
        slug: "op-silicone-halabuddy",
        name: "HalaBuddy silicone case",
        category: "accessory",
        art: "case",
        tint: "pink",
        tagline: "Shock-proof, 4 colors",
        price: 190000,
        rating: 4.6,
        sold: 2030,
        freeShipping: true,
        ages: ["4-8", "6-12"],
        colors: [
          { id: "pink", name: "Pink", hex: "#ff8fa3" },
          { id: "mint", name: "Mint", hex: "#7fd8c8" },
          { id: "yellow", name: "Yellow", hex: "#ffd166" },
          { id: "purple", name: "Purple", hex: "#b39ddb" },
        ],
        audience: "HalaBuddy Mini and HalaBuddy",
        summary: "Soft silicone case that absorbs drops without covering the speaker or microphones. Child-safe and washable.",
        highlights: ["Child-safe soft silicone", "Speaker/mic cut-outs", "4 colors"],
        features: [{ title: "Protection", body: "Cushions drops from up to 1 m." }],
        specs: [{ label: "Material", value: "Food-grade silicone" }],
        inBox: ["Silicone case"],
      },
      {
        slug: "bo-the-tu-vung-200",
        name: "200 vocabulary flashcards",
        category: "accessory",
        art: "cards",
        tint: "yellow",
        tagline: "12 topics, recognised by the robot from your child's reading",
        price: 149000,
        rating: 4.8,
        sold: 2870,
        freeShipping: true,
        ages: ["4-8", "6-12"],
        audience: "Children aged 4 – 12",
        summary: "200 sturdy double-sided cards: picture – word – phonetics. Your child reads the word, the robot scores pronunciation and gives an example sentence.",
        highlights: ["200 cards, 12 topics", "Thick, laminated card", "IPA phonetics"],
        features: [{ title: "Learn with the robot", body: "Flashcard mode on HalaBuddy recognises the word your child reads and responds instantly." }],
        specs: [{ label: "Card size", value: "9 × 6 cm" }],
        inBox: ["200 cards", "Storage box"],
      },
      {
        slug: "tui-dung-halabuddy",
        name: "HalaBuddy carry bag",
        category: "accessory",
        art: "bag",
        tint: "purple",
        tagline: "Take the robot to school or on holiday",
        price: 249000,
        rating: 4.7,
        sold: 640,
        freeShipping: true,
        ages: [],
        audience: "HalaBuddy Mini, HalaBuddy, HalaBuddy Pro",
        summary: "Padded bag with an accessory pocket, shoulder strap and smooth zip. Fits the robot and the dock.",
        highlights: ["Padded", "Accessory pocket", "Detachable strap"],
        features: [{ title: "Light", body: "Only 180 g, fits HalaBuddy Pro and the dock." }],
        specs: [{ label: "Size", value: "26 × 18 × 16 cm" }],
        inBox: ["Carry bag", "Shoulder strap"],
      },
      {
        slug: "goi-premium-12-thang",
        name: "Premium content plan — 12 months",
        category: "accessory",
        art: "premium",
        tint: "peach",
        tagline: "1,000+ extra lessons, exam practice & detailed reports",
        price: 599000,
        rating: 4.8,
        sold: 1180,
        freeShipping: true,
        ages: ["6-12", "9-15"],
        badge: "Online activation",
        audience: "HalaBuddy, HalaBuddy Pro (optional)",
        summary:
          "The robot works fully without this plan. Premium adds an extended lesson library, the complete Cambridge practice sets and per-sound pronunciation reports.",
        highlights: ["1,000+ extra lessons", "Full Starters – PET practice sets", "Per-sound pronunciation report", "Activation code via SMS/Zalo"],
        features: [{ title: "Optional", body: "The robot price already includes all core lessons; Premium is an add-on for fast learners." }],
        specs: [{ label: "Duration", value: "12 months from activation" }],
        inBox: ["Activation code (sent via SMS/Zalo/email)"],
      },
    ],
  },
  checkout: {
    title: "Checkout",
    subtitle: "Enter your delivery details and we'll call to confirm within 2 business hours.",
    noProduct: "Your cart is empty.",
    chooseProduct: "Choose a product",
    addMore: "Add more products",
    summary: "Your order",
    quantity: "Quantity",
    shipping: "Shipping",
    total: "Total",
    form: {
      name: "Full name",
      phone: "Phone number",
      email: "Email (optional)",
      address: "Delivery address",
      note: "Notes (child's age, preferred delivery time…)",
      payment: "Payment method",
      submit: "Place order",
      sending: "Sending…",
    },
    payments: [
      { id: "cod", name: "Cash on delivery (COD)", body: "Inspect the product, then pay the courier.", available: true },
      { id: "bank", name: "Bank transfer (VietQR)", body: "Scan a QR code with any Vietnamese banking app right after ordering — amount and note pre-filled, payment confirmed automatically.", available: true },
      { id: "online", name: "Online payment (MoMo, VNPay, card)", body: "Coming soon.", available: false },
    ],
    success: {
      title: "Order received!",
      body: "Thank you. TechHala will call to confirm your order within 2 business hours.",
      orderCode: "Order code",
      next: [
        "We call to confirm the address and delivery time.",
        "Delivery in 2 – 4 business days; inspect before paying.",
      ],
      bankNext: [
        "Scan the QR code below with your banking app — amount and note are pre-filled.",
        "Once the transfer lands, the order switches to “Paid” automatically (usually within 1 – 2 minutes).",
        "We pack and deliver within 2 – 4 business days.",
      ],
      track: "Track this order",
    },
    error: "We couldn't submit your order. Please call the hotline or try again.",
    errors: {
      outOfStock: "Some items in your cart are short on stock: {items}. Please lower the quantity or pick another colour.",
      tooMany: "This phone number has placed several orders in a short time. Please call the hotline and we'll help.",
    },
    support: { title: "Need help ordering?", body: "Call the hotline or message us on Zalo and we'll place the order for you in 2 minutes." },
  },
  orders: {
    title: "Track your order",
    subtitle: "Enter the order code from your confirmation and the phone number you used at checkout.",
    form: {
      code: "Order code",
      phone: "Phone number",
      submit: "Look up",
      searching: "Looking up…",
      notFound: "No order matches that code and phone number. Double-check both or call the hotline.",
    },
    detail: {
      title: "Order",
      placedAt: "Placed",
      status: "Status",
      payment: "Payment",
      paymentStatus: "Payment status",
      items: "Items",
      total: "Total",
      shipTo: "Deliver to",
      note: "Your note",
      history: "History",
      help: "Questions about this order? Call or message us on Zalo and quote the order code.",
      bankTitle: "Transfer to complete your order",
      bankBody: "Scan the VietQR code with any Vietnamese banking app — amount and note are pre-filled. Or transfer manually using the details below and keep the note exactly as shown.",
      bankBodyManual: "We'll call to confirm your order and send the account details by SMS/Zalo. Please use the transfer note below.",
      transferNote: "Transfer note",
      lookupAnother: "Look up another order",
      bank: {
        scan: "Scan with a banking app or e-wallet",
        bank: "Bank",
        accountNo: "Account number",
        accountName: "Account holder",
        amount: "Amount",
        copy: "Copy",
        copied: "Copied",
        auto: "Payment is confirmed automatically when the transfer arrives. Reload this page to see the latest status.",
        report: "I have transferred",
        reporting: "Sending…",
        reported: "Noted — we'll verify and update within a few minutes.",
        paid: "Payment received. Thank you!",
      },
    },
    statuses: {
      pending: "Received — awaiting confirmation",
      confirmed: "Confirmed",
      packed: "Packed",
      shipping: "Shipping",
      delivered: "Delivered",
      cancelled: "Cancelled",
      returned: "Returned",
    },
    paymentMethods: { cod: "Cash on delivery (COD)", bank: "Bank transfer" },
    paymentStatuses: { unpaid: "Unpaid", paid: "Paid", refunded: "Refunded" },
  },
  solutions: {
    title: "Enterprise AI solutions",
    subtitle:
      "Beyond AI robots for the family, TechHala deploys AI for software teams and enterprises: HAL‑SDLC for AI-driven software development, internal chatbots & AI assistants, and AI operations (AIOps).",
    sectionLabels: {
      problem: "The problem",
      approach: "Our approach",
      capabilities: "Capabilities",
      outcomes: "Outcomes",
      useCases: "Typical use cases",
    },
    relatedWork: "Related work",
    flagship: {
      eyebrow: "Platform",
      title: "HAL‑SDLC — AI for the software development lifecycle",
      body: "Describe what you want in plain language. HAL plans, orchestrates agents to build, runs adversarial review, and opens a pull request with a full audit trail — deployed inside your environment.",
      cta: "See HAL‑SDLC",
    },
    cta: {
      title: "Have a system to build — or one to keep running?",
      body: "Tell us about it. We'll come back with a concrete approach, not a slide deck.",
      button: "Start a conversation",
    },
    items: [
      {
        slug: "ai-robot",
        name: "AI Robot",
        tagline: "Intelligent robots that teach, talk, and learn with people.",
        summary:
          "We build the intelligence layer for educational and service robots: natural conversation, speech and vision, adaptive tutoring — starting with robots that help children and adults learn English.",
        problem: {
          title: "Robots can move. Very few can hold a conversation worth having.",
          body:
            "Most educational robots run scripted dialogues that children outgrow in a week, and language learners rarely get enough real speaking practice with a patient partner. The hardware exists — what's missing is intelligence that listens, understands, adapts to each learner, and stays safe for the classroom and the home.",
        },
        approach: {
          title: "Listen, understand, teach, adapt",
          steps: [
            { title: "Natural conversation", body: "Low-latency speech-to-speech with a consistent personality, so the robot feels like a companion, not a menu." },
            { title: "Pedagogy built in", body: "Lesson plans, vocabulary progression, pronunciation feedback, and games designed with educators and mapped to CEFR levels." },
            { title: "Perception & presence", body: "Vision and voice let the robot recognize learners, read engagement, and respond with expression and gesture." },
            { title: "Learn from every session", body: "Progress tracking for teachers and parents; the tutor adapts difficulty and topics to each learner." },
          ],
        },
        capabilities: [
          { title: "English-learning companion", body: "Conversational practice, pronunciation coaching, vocabulary games, and story time — tuned for kids and adult learners." },
          { title: "Conversational brain", body: "Speech recognition, LLM reasoning with guardrails, and expressive speech synthesis — running on-device or hybrid." },
          { title: "Vision & engagement", body: "Face and gesture recognition, attention cues, and object recognition for interactive lessons." },
          { title: "Teacher & parent dashboard", body: "Session summaries, progress by skill, and content controls." },
          { title: "Robot & hardware integration", body: "Integration with humanoid, tabletop, and mobile robot platforms — motion, LEDs, screens, and sensors." },
          { title: "Safety & privacy", body: "Age-appropriate content filters, on-device processing where possible, and parental consent flows." },
        ],
        outcomes: [
          "More speaking practice per learner than any classroom can offer",
          "Engagement that lasts beyond the novelty week",
          "Measurable progress for teachers and parents",
          "One intelligence platform across robot models",
        ],
        useCases: [
          "English-learning robots for kindergartens and primary schools",
          "Home tutoring companions for children",
          "Language centers and self-study kiosks",
          "Reception, museum, and service robots that converse naturally",
        ],
        cta: "Discuss an education robot project",
      },
      {
        slug: "ai-sdlc",
        name: "AI for SDLC",
        tagline: "Turn business intent into traceable, reviewed, working software.",
        summary:
          "An AI-driven software development lifecycle: plan, build, verify, and ship with specialized agents — and keep humans in control of every decision. Powered by our HAL-SDLC platform.",
        problem: {
          title: "Code assistants speed up typing. They don't speed up delivery.",
          body:
            "Teams adopting AI coding tools see faster snippets but the same bottlenecks: unclear requirements, unreviewed output, inconsistent standards, and no record of why something was built. The result is more code with less confidence.",
        },
        approach: {
          title: "Lifecycle first, code second",
          steps: [
            {
              title: "Structured planning",
              body: "Business intent becomes a plan with acceptance criteria, architecture notes, and a dependency graph — reviewable before any code exists.",
            },
            {
              title: "Orchestrated build",
              body: "Specialized agents implement in parallel by phase, grounded in your conventions, documentation, and past decisions.",
            },
            {
              title: "Independent verification",
              body: "Separate reviewer agents score every deliverable across correctness, quality, security, and tests. Nothing merges on trust alone.",
            },
            {
              title: "Continuous learning",
              body: "Each cycle captures learnings back into the knowledge layer, so the next plan is better than the last.",
            },
          ],
        },
        capabilities: [
          { title: "HAL-SDLC platform", body: "Our engine for AI-driven planning, execution, and review — deployed inside your environment." },
          { title: "Agent enablement", body: "Skills, rules, and context so agents follow your architecture and standards." },
          { title: "Knowledge layer", body: "Your docs, ADRs, and codebase distilled into a searchable wiki agents actually use." },
          { title: "Quality gates", body: "Multi-persona review, security audit, test generation, and pre-ship polish." },
          { title: "IDE & MCP integration", body: "Works with Cursor and any MCP-compatible tooling your developers already use." },
          { title: "Adoption program", body: "Pilot, measure, and roll out across teams with clear governance." },
        ],
        outcomes: [
          "Faster idea-to-PR cycle with fewer review rounds",
          "Consistent standards across teams and repositories",
          "A complete audit trail for every AI-generated change",
          "Developers focused on judgment, not boilerplate",
        ],
        useCases: [
          "Modernizing a legacy platform module by module",
          "Building internal tools and customer portals at speed",
          "Scaling engineering output without scaling headcount",
          "Regulated environments that require traceability",
        ],
        cta: "Discuss an AI SDLC pilot",
      },
      {
        slug: "ai-enterprise",
        name: "AI for Enterprise",
        tagline: "Chatbots, assistants, and AI services deployed securely inside your organization.",
        summary:
          "From customer-facing chatbots to internal copilots and private AI platforms — we design, build, deploy, and operate AI services that fit your data, your systems, and your compliance requirements.",
        problem: {
          title: "A demo takes a day. A production AI service takes discipline.",
          body:
            "Prototypes with large language models are easy. Reliable enterprise services — grounded in your data, integrated with your systems, secured, evaluated, cost-controlled, and monitored in production — are where most initiatives stall.",
        },
        approach: {
          title: "From use case to running service",
          steps: [
            { title: "Discover", body: "Identify the highest-value use cases, data sources, and success metrics with your business and IT teams." },
            { title: "Design", body: "Conversation design, knowledge architecture, and integration blueprint aligned with security and compliance." },
            { title: "Build & integrate", body: "Retrieval, orchestration, guardrails, and connectors to CRM, ERP, ticketing, and identity systems." },
            { title: "Deploy & operate", body: "Private or hybrid deployment, observability, cost management, evaluation, and continuous improvement." },
          ],
        },
        capabilities: [
          { title: "Customer service chatbots", body: "Multilingual assistants for web, app, and messaging channels — grounded in your knowledge with human handoff." },
          { title: "Employee assistants & copilots", body: "Internal copilots for HR, IT, sales, and operations that answer from policies and act in your tools." },
          { title: "Knowledge hubs & RAG", body: "Documents, databases, and tickets turned into trusted answers with citations and access control." },
          { title: "Private AI platform", body: "LLM gateway, model hosting, and vector infrastructure deployed in your cloud or on-premises." },
          { title: "AI service operations", body: "Monitoring, evaluation, cost control, and incident response for AI in production — including AIOps for your platforms." },
          { title: "Generative content & data products", body: "Image, video, and document generation pipelines plus data-rich applications built for scale." },
        ],
        outcomes: [
          "Assistants that resolve requests, not just deflect them",
          "Answers grounded in your data, with sources and permissions respected",
          "Predictable costs and measurable quality after launch",
          "A platform you own — no vendor lock-in",
        ],
        useCases: [
          "Customer support and sales assistants for retail, banking, and telecom",
          "Internal knowledge assistants for large organizations",
          "Deploying private LLM services for regulated industries",
          "Content, media, and data platforms powered by generative AI",
        ],
        cta: "Discuss an enterprise AI project",
      },
    ],
  },
  product: {
    eyebrow: "Product",
    title: "HAL-SDLC",
    subtitle:
      "The Heuristic AI Lifecycle for software development. Describe intent in plain language — HAL plans, orchestrates specialized agents, reviews adversarially, and ships with a full audit trail. Deployed privately, inside your environment.",
    primaryCta: "Request a private demo",
    secondaryCta: "Explore the AI SDLC approach",
    terminal: [
      {
        cmd: 'hal plan "Customer portal with SSO and usage dashboard"',
        out: [
          "✓ Template selected: fullstack-feature",
          "✓ 6 sub-PRPs, 3 execution phases, DAG resolved",
          "✓ Architecture notes + acceptance criteria written",
        ],
      },
      {
        cmd: "hal execute",
        out: [
          "→ Phase 1/3: auth-service, schema  (2 agents)",
          "→ Phase 2/3: api, dashboard-ui     (2 agents)",
          "→ Phase 3/3: e2e-tests             (1 agent)",
        ],
      },
      {
        cmd: "hal review",
        out: [
          "10 personas · 0 P0 · 1 P2 autofixed",
          "Score 91/100 — APPROVED",
          "✓ Pull request opened with full audit trail",
        ],
      },
    ],
    stats: [
      { value: "35+", label: "CLI commands" },
      { value: "10", label: "review personas" },
      { value: "8", label: "specialized templates" },
      { value: "100%", label: "traceable decisions" },
    ],
    workflow: {
      title: "How it works",
      steps: [
        { name: "Plan", desc: "One sentence of intent becomes a structured pack: index, sub-tasks, architecture notes, acceptance criteria, and a dependency graph." },
        { name: "Validate", desc: "Structural gates score the plan before anyone writes code. Plan-level bugs are fixed where they're cheapest." },
        { name: "Execute", desc: "Agents implement in parallel by phase — engineers, reviewers, and planners each with a defined role." },
        { name: "Review", desc: "Independent reviewers with 10 personas score every deliverable with severity and confidence. Bounded autofix handles the small stuff." },
        { name: "Ship", desc: "Conventional commits, pull requests, and a complete decision log — ready for human approval." },
        { name: "Compound", desc: "Learnings are captured into the knowledge layer so the next cycle starts smarter." },
      ],
    },
    features: {
      title: "What sets it apart",
      items: [
        { title: "Plans your team can review", body: "Every build starts from a specification with explicit acceptance criteria and evidence — not from a chat transcript." },
        { title: "Multi-agent orchestration", body: "Dependency-aware phases assign work to specialized agents and keep them coordinated." },
        { title: "Adversarial review", body: "Architecture, security, performance, and adversarial personas review independently. Findings carry severity and confidence." },
        { title: "Three-layer knowledge", body: "Your documents, distilled and compiled into an interlinked wiki that agents query before they build." },
        { title: "Solo and full modes", body: "Lightweight flow for single-developer tasks; full orchestration for multi-service work. Same quality bar." },
        { title: "Privacy by default", body: "Runs in your environment. Sensitive names and terms are redacted from generated artifacts automatically." },
      ],
    },
    audiences: {
      title: "Who it's for",
      items: [
        { title: "Engineering leaders", body: "Scale delivery with governance, standards, and visibility built in." },
        { title: "Platform & DevEx teams", body: "Give every developer the same context, conventions, and quality gates." },
        { title: "Regulated industries", body: "Traceability from requirement to commit satisfies audit and compliance needs." },
      ],
    },
    delivery: {
      title: "Delivery & licensing",
      body: "HAL-SDLC is licensed privately to organizations and deployed within your own infrastructure. Commercial terms, support tiers, and update cadence are defined per agreement.",
      items: [
        "Private distribution — tagged releases or checksummed archives",
        "Works with Cursor and MCP-compatible tooling",
        "Installation, onboarding, and support included per tier",
        "Optional customization of templates, skills, and review personas",
      ],
    },
    faq: {
      title: "Frequently asked",
      items: [
        { q: "Does HAL replace our developers?", a: "No. HAL removes boilerplate and coordination overhead so developers spend their time on judgment, architecture, and review. A human approves every pull request." },
        { q: "Which languages and stacks are supported?", a: "HAL is stack-agnostic at the planning and review level and ships templates for TypeScript, Python, and common web and service architectures. Additional stacks are added through templates and distillations." },
        { q: "Where does our code go?", a: "Nowhere. HAL runs inside your environment and connects to the model providers you approve. Generated artifacts stay in your repositories." },
        { q: "How do we start?", a: "A short pilot on a real backlog item: we install HAL, plan and execute together, and measure cycle time and review quality against your baseline." },
      ],
    },
  },
  work: {
    title: "Work",
    subtitle: "Selected solutions we've designed and delivered. Details are shared under NDA where required.",
    items: [
      {
        slug: "enterprise-virtual-assistant",
        title: "Enterprise virtual assistant for a retail group",
        client: "Retail & consumer",
        industry: "Retail",
        pillar: "ai-enterprise",
        summary: "A multilingual virtual assistant that answers customer and staff questions from company knowledge and connects to internal systems.",
        challenge: "Support teams handled repetitive questions across channels while policies and product information changed weekly. Existing chatbots were rule-based and fell behind.",
        solution: "We designed a retrieval-grounded assistant with conversation design tailored to the brand, connected to knowledge sources and internal APIs, with evaluation and escalation to human agents built in.",
        results: ["Consistent answers across web and messaging channels", "Knowledge updates reflected without retraining", "Clear handoff to human agents with full context"],
      },
      {
        slug: "voice-ai-companion",
        title: "Real-time voice companion for conversation practice",
        client: "Consumer app",
        industry: "Education & consumer",
        pillar: "ai-robot",
        summary: "A speech-to-speech companion where learners talk with characters that have their own persona, voice, and animated face — the conversational brain we bring to educational robots.",
        challenge: "Deliver natural, low-latency voice conversations with expressive, lip-synced avatars across iOS, Android, and web — engaging enough that learners keep practicing.",
        solution: "We built a multimodal pipeline — speech recognition, in-character reasoning with guardrails, high-quality speech synthesis, and lip-synced video — behind a mobile-first experience for creating and talking with companions.",
        results: ["Cross-platform release from a single codebase", "Persona-consistent conversations with custom voices", "Same pipeline now powering robot conversation and tutoring"],
      },
      {
        slug: "generative-film-pipeline",
        title: "Generative image & video pipeline for film concepts",
        client: "Media & entertainment",
        industry: "Media",
        pillar: "ai-enterprise",
        summary: "A production pipeline that turns scripts and prompts into consistent concept imagery and short video sequences.",
        challenge: "Concept development for film required many iterations of visuals and motion tests that were slow and expensive to produce traditionally.",
        solution: "We built an orchestrated pipeline using state-of-the-art image and video generation models with prompt management, style consistency, and review workflows for the creative team.",
        results: ["Concept iterations in hours instead of weeks", "Consistent visual style across scenes", "Creative team focused on direction, not tooling"],
      },
      {
        slug: "geospatial-heritage-platform",
        title: "Nationwide geospatial heritage platform",
        client: "Culture & tourism",
        industry: "Public & tourism",
        pillar: "ai-enterprise",
        summary: "A bilingual, map-based registry of more than 3,000 cultural sites with AI-assisted data enrichment and search-optimized pages.",
        challenge: "Site information was scattered across sources, inconsistent, and unavailable in a modern, searchable format.",
        solution: "We built automated ingestion and AI-assisted enrichment pipelines, a clustered interactive map, and thousands of statically generated bilingual pages optimized for search and mobile.",
        results: ["3,000+ sites mapped and enriched", "Fast, static-first pages ranking for local search", "Bilingual content with province, route, and festival discovery"],
      },
      {
        slug: "ai-sdlc-adoption",
        title: "AI SDLC engine built with itself",
        client: "TechHala",
        industry: "Software",
        pillar: "ai-sdlc",
        summary: "HAL-SDLC's own skills, agents, and services are planned, built, and reviewed by HAL — the strongest test of the approach.",
        challenge: "Prove that AI-driven planning and multi-agent execution can produce production-grade software with traceability, not just demos.",
        solution: "Every new capability — from review personas to internal APIs — runs through HAL's plan → execute → review → ship loop, with learnings compounded back into the knowledge layer.",
        results: ["Self-bootstrapping platform with a full decision log", "Independent review on every deliverable", "Methodology validated before offering it to customers"],
      },
    ],
  },
  about: {
    title: "About TechHala",
    subtitle: "An AI engineering studio building intelligence for robots, software teams, and the enterprise.",
    mission: {
      title: "Our mission",
      body: "Make AI a dependable engineering discipline — traceable, reviewable, and in production — whether it teaches a child, builds software, or serves an organization.",
    },
    values: [
      { title: "Traceable by default", body: "Every AI decision should have a reason you can read and a record you can audit." },
      { title: "Humans in control", body: "Agents do the work; people make the calls. We design for approval gates, not blind automation." },
      { title: "Production over demos", body: "We measure ourselves by what runs reliably for users, not what looks good in a video." },
      { title: "Compound learning", body: "Every project feeds knowledge back into the next one — for us and for our clients." },
    ],
    story: {
      title: "Our story",
      paragraphs: [
        "TechHala started with a simple frustration: AI could write code, but nobody could explain why it wrote what it did — or trust it enough to ship. We set out to build the missing lifecycle around AI: planning, verification, and operations.",
        "That work became HAL-SDLC, our AI software development lifecycle engine, and shaped how we approach every problem — from deploying AI services inside enterprises to giving educational robots a voice that listens, understands, and teaches.",
        "Today we partner with organizations in Vietnam and internationally to design, build, and operate AI systems that hold up in the real world.",
      ],
    },
    stats: [
      { value: "3", label: "focus areas" },
      { value: "1", label: "flagship platform" },
      { value: "VN + Global", label: "clients served" },
      { value: "100%", label: "human-approved delivery" },
    ],
  },
  contact: {
    title: "Contact TechHala",
    subtitle: "Advice on choosing a robot, order and warranty support, or a conversation about enterprise AI. Call the hotline for an immediate answer, or send the form — we reply within 1 business day.",
    form: {
      name: "Name",
      email: "Email or phone",
      company: "Company / School (optional)",
      topic: "I need",
      topics: ["Advice on buying a robot", "Order & warranty support", "Bulk order for a school / centre", "AI for SDLC / HAL-SDLC", "AI for Enterprise / AIOps", "Other"],
      message: "Message (child's age, needs, questions…)",
      submit: "Send message",
      sending: "Sending…",
      success: "Thanks — we've received your message and will be in touch shortly.",
      error: "Something went wrong. Please email us directly instead.",
    },
    aside: {
      title: "Call or visit us",
      body: "Hotline and Zalo are open 8:30 – 18:00 on weekdays. You're welcome to try the robots in person at our office.",
      hours: "Mon – Sat · 8:30 – 18:00",
      visit: "Open in Maps",
    },
  },
  footer: {
    tagline: "English-learning AI robots for students and AI assistants for Vietnamese families — developed by TechHala in Hanoi.",
    products: "Products",
    solutions: "Solutions",
    company: "Company",
    contact: "Contact",
    rights: "All rights reserved.",
    trackOrder: "Track order",
  },
};
