import type { Dictionary } from "./types";

export const vi: Dictionary = {
  meta: {
    title: "TechHala — Robot AI học tiếng Anh & trợ lý gia đình",
    description:
      "Robot AI TechHala giúp học sinh luyện nói tiếng Anh mỗi ngày và trợ lý AI cho gia đình Việt. Giá từ 2 – 4 triệu đồng, giao hàng toàn quốc, thanh toán khi nhận hàng. Hotline (+84) 0868 862 564.",
    ogTitle: "TechHala — Robot AI cho học sinh & gia đình, giá từ 2 triệu",
  },
  nav: {
    products: "Sản phẩm",
    solutions: "Giải pháp",
    work: "Dự án",
    about: "Về chúng tôi",
    contact: "Liên hệ",
    shopNow: "Mua ngay",
    menu: "Menu",
    close: "Đóng",
  },
  common: {
    learnMore: "Tìm hiểu thêm",
    viewAll: "Xem tất cả",
    back: "Quay lại",
    talkToUs: "Trao đổi với chúng tôi",
    industry: "Lĩnh vực",
    challenge: "Thách thức",
    solution: "Giải pháp",
    results: "Kết quả",
    relatedSolution: "Giải pháp liên quan",
    theme: "Đổi giao diện",
    language: "Ngôn ngữ",
  },
  shop: {
    priceFrom: "Giá từ",
    buyNow: "Mua ngay",
    addToOrder: "Đặt mua",
    viewDetails: "Xem chi tiết",
    contactUs: "Liên hệ tư vấn",
    callUs: "Gọi ngay",
    zalo: "Chat Zalo",
    email: "Email",
    address: "Địa chỉ",
    phone: "Hotline",
    categories: {
      education: {
        name: "Robot AI học tiếng Anh",
        short: "Bạn học nói tiếng Anh mỗi ngày cho học sinh 4 – 15 tuổi.",
      },
      home: {
        name: "Robot AI cho gia đình",
        short: "Trợ lý gia đình: nhắc việc, trò chuyện, kết nối, chăm sóc ông bà.",
      },
      combo: {
        name: "Combo tiết kiệm",
        short: "Mua theo bộ cho anh em, cả nhà — tiết kiệm đến 400.000đ.",
      },
      accessory: {
        name: "Phụ kiện & nội dung",
        short: "Đế sạc, ốp bảo vệ, thẻ từ vựng và gói nội dung Premium.",
      },
    },
    ages: {
      "4-8": { name: "4 – 8 tuổi", short: "Mầm non, lớp 1 – 3 · làm quen tiếng Anh qua bài hát, truyện" },
      "6-12": { name: "6 – 12 tuổi", short: "Tiểu học · luyện nói theo bài trên lớp, Cambridge Starters – Flyers" },
      "9-15": { name: "9 – 15 tuổi", short: "THCS · luyện thi KET/PET, thuyết trình, viết" },
      family: { name: "Cả gia đình", short: "Trợ lý phòng khách · nhắc lịch, gọi video, nhà thông minh" },
      seniors: { name: "Ông bà", short: "Nhắc thuốc, đọc báo, trò chuyện, gọi con cháu" },
    },
    labels: {
      audience: "Dành cho",
      highlights: "Điểm nổi bật",
      features: "Tính năng",
      specs: "Thông số",
      inBox: "Trong hộp có gì",
      related: "Sản phẩm khác",
      allProducts: "Tất cả sản phẩm",
      priceNote: "Giá đã gồm VAT · Miễn phí giao hàng toàn quốc · Bảo hành 12 tháng",
      freeShipping: "Freeship",
      sold: "đã bán",
      reviews: "đánh giá",
      save: "Tiết kiệm",
      color: "Màu sắc",
      age: "Độ tuổi",
      inStock: "Còn hàng · Giao 2 – 4 ngày",
      filterAll: "Tất cả",
      filterCategory: "Danh mục",
      filterAge: "Độ tuổi",
      filterPrice: "Mức giá",
      sortBy: "Sắp xếp",
      sortOptions: [
        { id: "popular", label: "Bán chạy" },
        { id: "price-asc", label: "Giá thấp → cao" },
        { id: "price-desc", label: "Giá cao → thấp" },
        { id: "rating", label: "Đánh giá cao" },
      ],
      result: "sản phẩm",
      results: "sản phẩm",
      noResults: "Không có sản phẩm phù hợp bộ lọc. Thử bỏ bớt bộ lọc nhé.",
      clearFilters: "Xoá bộ lọc",
      priceRanges: [
        { id: "under-1m", label: "Dưới 1 triệu", min: 0, max: 1000000 },
        { id: "2m-3m", label: "2 – 3 triệu", min: 2000000, max: 3000000 },
        { id: "3m-4m", label: "3 – 4 triệu", min: 3000000, max: 4000000 },
        { id: "over-4m", label: "Trên 4 triệu (combo)", min: 4000000 },
      ],
    },
    cart: {
      title: "Giỏ hàng",
      open: "Mở giỏ hàng",
      close: "Đóng giỏ hàng",
      empty: "Giỏ hàng đang trống.",
      emptyCta: "Xem sản phẩm",
      addToCart: "Thêm vào giỏ",
      added: "Đã thêm vào giỏ",
      remove: "Xoá",
      subtotal: "Tạm tính",
      shippingFree: "Miễn phí giao hàng toàn quốc",
      checkout: "Thanh toán",
      continueShopping: "Tiếp tục mua sắm",
      items: "sản phẩm",
      quantity: "Số lượng",
    },
    guarantees: [
      { title: "Bảo hành 12 tháng", body: "Đổi mới trong 30 ngày đầu nếu lỗi do nhà sản xuất." },
      { title: "Giao hàng toàn quốc", body: "Miễn phí giao hàng, nhận hàng trong 2 – 4 ngày làm việc." },
      { title: "Thanh toán linh hoạt", body: "Thanh toán khi nhận hàng (COD) hoặc chuyển khoản ngân hàng." },
      { title: "Hỗ trợ tận tình", body: "Hotline & Zalo hỗ trợ cài đặt, hướng dẫn phụ huynh và học sinh." },
    ],
  },
  home: {
    hero: {
      eyebrow: "Robot AI TechHala",
      title: "Bạn học tiếng Anh",
      highlight: "biết lắng nghe.",
      subtitle:
        "Robot AI giúp con luyện nói tiếng Anh mỗi ngày như trò chuyện với bạn thật — sửa phát âm, kể chuyện, chơi trò chơi từ vựng. Và robot trợ lý cho cả gia đình: nhắc lịch, trò chuyện với ông bà, kết nối mọi người.",
      primaryCta: "Xem sản phẩm",
      secondaryCta: "Gọi tư vấn",
      bullets: ["Giá 2 – 4 triệu đồng", "Giao hàng toàn quốc", "Thanh toán khi nhận hàng", "Bảo hành 12 tháng"],
      priceBadge: "Chỉ từ",
    },
    strip: ["Freeship toàn quốc", "Thanh toán khi nhận hàng", "Bảo hành 12 tháng · đổi mới 30 ngày", "Hotline (+84) 0868 862 564"],
    stats: [
      { value: "5.000+", label: "gia đình đang dùng" },
      { value: "4.8/5", label: "phụ huynh đánh giá" },
      { value: "2 – 4 tr", label: "giá robot" },
      { value: "12 th", label: "bảo hành" },
    ],
    bubbles: { robot: "Hi! What did you eat for lunch today? 🍜", child: "I ate… phở! It was yummy!" },
    ages: {
      eyebrow: "Chọn theo độ tuổi",
      title: "Con bạn bao nhiêu tuổi?",
      subtitle: "Mỗi độ tuổi có một robot phù hợp với trình độ và cách học. Chọn để xem gợi ý.",
    },
    categories: {
      eyebrow: "Danh mục",
      title: "Chọn robot phù hợp với gia đình bạn",
      subtitle: "Hai dòng sản phẩm, cùng một trí tuệ AI được TechHala phát triển và cập nhật liên tục.",
    },
    catalog: {
      eyebrow: "Bán chạy",
      title: "Robot được bố mẹ chọn nhiều nhất",
      subtitle: "Tất cả sản phẩm đều có giá niêm yết, mua trực tiếp trên website hoặc gọi hotline để được tư vấn.",
    },
    bundles: {
      eyebrow: "Combo & phụ kiện",
      title: "Mua theo bộ, tiết kiệm hơn",
      subtitle: "Combo cho anh em, cả nhà và phụ kiện chính hãng: đế sạc, ốp, thẻ từ vựng, gói Premium.",
    },
    testimonials: {
      eyebrow: "Bố mẹ nói gì",
      title: "Hơn 5.000 gia đình đã tin dùng",
      items: [
        {
          quote: "Bé nhà mình 6 tuổi, trước rất ngại nói tiếng Anh. Sau 3 tuần với HalaBuddy Mini, tối nào cũng đòi ‘chat with robot’ trước khi ngủ.",
          name: "Chị Minh Anh",
          role: "Mẹ bé Bông, Hà Nội",
        },
        {
          quote: "Điểm Speaking của con tăng rõ, cô giáo khen phát âm tốt hơn hẳn. Mình thích nhất báo cáo hằng tuần, biết con học gì.",
          name: "Anh Quốc Huy",
          role: "Bố bé Nam lớp 5, TP.HCM",
        },
        {
          quote: "Mua HalaCare cho bà ở quê. Bà uống thuốc đúng giờ, gọi được cháu chỉ bằng một câu nói. Cả nhà yên tâm hơn nhiều.",
          name: "Chị Thu Hà",
          role: "Đà Nẵng",
        },
      ],
    },
    why: {
      eyebrow: "Vì sao chọn TechHala",
      title: "Robot do TechHala tự phát triển — không phải đồ chơi lập trình sẵn",
      subtitle:
        "Trí tuệ bên trong robot là công nghệ AI hội thoại mà TechHala đang triển khai cho doanh nghiệp, được tinh chỉnh cho trẻ em và gia đình Việt.",
      items: [
        {
          title: "Hội thoại tự nhiên, có sửa lỗi",
          body: "Robot hiểu câu nói chưa hoàn chỉnh của trẻ, phản hồi tự nhiên và nhẹ nhàng sửa phát âm, ngữ pháp ngay trong cuộc trò chuyện.",
        },
        {
          title: "Theo đúng chương trình học",
          body: "Nội dung bám sát chương trình tiếng Anh tiểu học – THCS và các khung Cambridge Starters/Movers/Flyers, KET, PET.",
        },
        {
          title: "Phụ huynh nắm rõ tiến bộ",
          body: "Báo cáo hằng tuần qua ứng dụng: thời gian luyện nói, từ mới, lỗi phát âm hay gặp và gợi ý cho bố mẹ.",
        },
        {
          title: "An toàn cho trẻ",
          body: "Nội dung được lọc theo lứa tuổi, không quảng cáo, không mạng xã hội. Dữ liệu giọng nói được bảo vệ và có thể xoá bất kỳ lúc nào.",
        },
        {
          title: "Nói được tiếng Việt",
          body: "Robot giải thích bằng tiếng Việt khi con chưa hiểu, rồi khuyến khích con quay lại nói tiếng Anh.",
        },
        {
          title: "Cập nhật liên tục",
          body: "Bài học, trò chơi và giọng nói mới được cập nhật tự động qua Wi‑Fi — robot ngày càng thông minh hơn.",
        },
      ],
    },
    steps: {
      eyebrow: "Mua hàng đơn giản",
      title: "Từ đặt hàng đến buổi học đầu tiên",
      subtitle: "Bốn bước, không cần kiến thức kỹ thuật.",
      items: [
        { name: "Chọn robot", desc: "Chọn sản phẩm phù hợp độ tuổi và nhu cầu, hoặc gọi hotline để được tư vấn." },
        { name: "Đặt hàng", desc: "Điền thông tin giao hàng, chọn thanh toán khi nhận hàng hoặc chuyển khoản." },
        { name: "Nhận hàng", desc: "Giao tận nhà trong 2 – 4 ngày làm việc, kiểm tra hàng trước khi thanh toán." },
        { name: "Bắt đầu học", desc: "Kết nối Wi‑Fi, tạo hồ sơ cho con trong 5 phút và bắt đầu buổi trò chuyện đầu tiên." },
      ],
    },
    family: {
      eyebrow: "Robot AI cho gia đình",
      title: "Không chỉ cho con — một trợ lý cho cả nhà",
      body:
        "Dòng HalaHome và HalaCare mang trí tuệ hội thoại vào phòng khách: nhắc lịch học, lịch uống thuốc, đọc tin thời tiết, gọi video cho người thân và trò chuyện với ông bà khi con cháu đi làm.",
      bullets: [
        "Nhắc việc, nhắc thuốc, báo thức bằng giọng nói tự nhiên",
        "Gọi nhanh người thân chỉ bằng một câu nói",
        "Trò chuyện, đọc báo, kể chuyện, nghe nhạc cho người lớn tuổi",
        "Điều khiển đèn, quạt, TV tương thích trong nhà",
      ],
      cta: "Xem robot gia đình",
    },
    faq: {
      title: "Câu hỏi thường gặp",
      items: [
        {
          q: "Robot có cần kết nối Internet không?",
          a: "Có. Robot dùng Wi‑Fi gia đình để hội thoại và cập nhật bài học. Một số trò chơi và bài hát vẫn dùng được khi mất mạng.",
        },
        {
          q: "Con tôi 5 tuổi chưa biết chữ, có dùng được không?",
          a: "Được. HalaBuddy Mini thiết kế cho trẻ 4 – 8 tuổi, hoàn toàn bằng giọng nói, không cần đọc chữ.",
        },
        {
          q: "Có phải trả phí hằng tháng không?",
          a: "Không bắt buộc. Giá mua đã bao gồm bài học cơ bản và cập nhật phần mềm, không phát sinh phí thuê bao. Gói Premium là tuỳ chọn thêm nếu bố mẹ muốn nhiều bài học và đề luyện thi hơn.",
        },
        {
          q: "Thanh toán như thế nào?",
          a: "Bạn có thể thanh toán khi nhận hàng (COD) trên toàn quốc hoặc chuyển khoản ngân hàng sau khi nhân viên xác nhận đơn.",
        },
        {
          q: "Bảo hành ra sao?",
          a: "Bảo hành 12 tháng, đổi mới trong 30 ngày nếu lỗi do nhà sản xuất. Hỗ trợ kỹ thuật qua hotline và Zalo.",
        },
        {
          q: "Mua số lượng lớn cho trường học, trung tâm?",
          a: "Có chính sách giá riêng và tài khoản quản lý lớp cho trường học, trung tâm tiếng Anh. Liên hệ hotline để được báo giá.",
        },
      ],
    },
    solutions: {
      eyebrow: "Dành cho doanh nghiệp",
      title: "TechHala còn xây dựng AI cho đội ngũ phần mềm và doanh nghiệp",
      body:
        "Công nghệ AI đứng sau robot cũng được TechHala triển khai cho khách hàng doanh nghiệp: nền tảng HAL‑SDLC cho phát triển phần mềm bằng AI, chatbot & trợ lý AI nội bộ, vận hành hệ thống AI (AIOps).",
      cta: "Xem giải pháp doanh nghiệp",
    },
    cta: {
      title: "Chưa biết chọn robot nào cho con?",
      body: "Gọi hoặc nhắn Zalo cho chúng tôi — đội ngũ TechHala sẽ tư vấn theo độ tuổi, trình độ và mục tiêu học của con trong 10 phút.",
      primary: "Gọi (+84) 0868 862 564",
      secondary: "Gửi yêu cầu tư vấn",
    },
  },
  products: {
    title: "Sản phẩm robot AI",
    subtitle:
      "Robot AI học tiếng Anh cho học sinh và robot trợ lý gia đình do TechHala phát triển. Giá niêm yết 2 – 4 triệu đồng, giao hàng toàn quốc.",
    items: [
      {
        slug: "halabuddy-mini",
        name: "HalaBuddy Mini",
        category: "education",
        art: "mini",
        tint: "pink",
        tagline: "Robot học tiếng Anh cho bé 4 – 8 tuổi",
        price: 2290000,
        compareAtPrice: 2590000,
        rating: 4.8,
        sold: 1240,
        freeShipping: true,
        ages: ["4-8"],
        ageLabel: "4 – 8 tuổi",
        colors: [
          { id: "pink", name: "Hồng", hex: "#ff8fa3" },
          { id: "mint", name: "Xanh mint", hex: "#7fd8c8" },
          { id: "yellow", name: "Vàng", hex: "#ffd166" },
        ],
        badge: "Cho bé mới bắt đầu",
        audience: "Trẻ 4 – 8 tuổi, mầm non và lớp 1 – 3",
        summary:
          "Bạn học nhỏ gọn, hoàn toàn bằng giọng nói. Bé làm quen tiếng Anh qua bài hát, kể chuyện, trò chơi đoán từ và những cuộc trò chuyện ngắn vui vẻ mỗi ngày.",
        highlights: [
          "300+ bài hát, truyện kể và trò chơi từ vựng",
          "Nhận diện giọng trẻ em, phản hồi nhẹ nhàng",
          "Không màn hình — bảo vệ mắt bé",
          "Giới hạn thời gian sử dụng theo cài đặt của bố mẹ",
        ],
        features: [
          { title: "Trò chuyện theo chủ đề", body: "Màu sắc, con vật, gia đình, đồ ăn… mỗi ngày một chủ đề, mỗi buổi 10 – 15 phút." },
          { title: "Học qua bài hát và truyện", body: "Thư viện bài hát và truyện kể tiếng Anh theo lứa tuổi, có phiên bản chậm để bé nhại theo." },
          { title: "Khen thưởng và huy hiệu", body: "Bé nhận huy hiệu khi hoàn thành chuỗi ngày học, bố mẹ xem trên ứng dụng." },
          { title: "Chế độ song ngữ", body: "Robot giải thích bằng tiếng Việt khi bé chưa hiểu, sau đó quay lại tiếng Anh." },
        ],
        specs: [
          { label: "Kích thước", value: "14 × 10 × 10 cm · 420 g" },
          { label: "Pin", value: "6 – 8 giờ sử dụng, sạc USB‑C" },
          { label: "Kết nối", value: "Wi‑Fi 2.4 GHz, Bluetooth 5.0" },
          { label: "Âm thanh", value: "Loa 3 W, 2 micro khử ồn" },
          { label: "Ứng dụng", value: "TechHala Parent (iOS/Android)" },
        ],
        inBox: ["Robot HalaBuddy Mini", "Cáp sạc USB‑C", "Sổ tay hướng dẫn song ngữ", "Bộ thẻ từ vựng 50 thẻ"],
      },
      {
        slug: "halabuddy",
        name: "HalaBuddy",
        category: "education",
        art: "buddy",
        tint: "yellow",
        tagline: "Bạn luyện nói tiếng Anh cho học sinh tiểu học – THCS",
        price: 2990000,
        compareAtPrice: 3490000,
        rating: 4.9,
        sold: 3120,
        freeShipping: true,
        ages: ["6-12", "9-15"],
        ageLabel: "6 – 15 tuổi",
        colors: [
          { id: "white", name: "Trắng", hex: "#f4f4f4" },
          { id: "red", name: "Đỏ TechHala", hex: "#e60012" },
          { id: "blue", name: "Xanh dương", hex: "#4f8ef7" },
        ],
        badge: "Bán chạy nhất",
        audience: "Học sinh 6 – 15 tuổi, lớp 1 – 9",
        summary:
          "Robot hội thoại đầy đủ: luyện nói theo chương trình học, chấm phát âm từng câu, ôn từ vựng theo bài trên lớp và báo cáo tiến bộ hằng tuần cho phụ huynh.",
        highlights: [
          "Luyện nói theo chương trình tiểu học – THCS và Cambridge YLE",
          "Chấm phát âm từng câu, gợi ý sửa lỗi",
          "Ôn từ vựng theo bài học trên lớp",
          "Báo cáo tiến bộ hằng tuần cho phụ huynh",
        ],
        features: [
          { title: "Hội thoại theo tình huống", body: "Đi mua sắm, giới thiệu bản thân, kể về ngày nghỉ… hơn 500 tình huống theo cấp độ." },
          { title: "Chấm phát âm chi tiết", body: "Điểm phát âm theo từng âm, từ và câu; robot đọc mẫu và cho con nói lại." },
          { title: "Đồng bộ bài học trên lớp", body: "Chọn bộ sách con đang học (Global Success, Family & Friends, i‑Learn Smart Start…) để robot ôn đúng bài." },
          { title: "Luyện thi Cambridge", body: "Đề luyện Starters, Movers, Flyers phần Speaking với phản hồi ngay." },
          { title: "Ứng dụng phụ huynh", body: "Xem thời gian học, từ mới, lỗi thường gặp; đặt giờ học và giới hạn sử dụng." },
        ],
        specs: [
          { label: "Kích thước", value: "18 × 12 × 12 cm · 650 g" },
          { label: "Pin", value: "8 – 10 giờ, sạc USB‑C" },
          { label: "Kết nối", value: "Wi‑Fi 2.4/5 GHz, Bluetooth 5.0" },
          { label: "Âm thanh", value: "Loa 5 W, 4 micro định hướng" },
          { label: "Hiển thị", value: "Màn LED biểu cảm" },
          { label: "Ứng dụng", value: "TechHala Parent (iOS/Android)" },
        ],
        inBox: ["Robot HalaBuddy", "Đế sạc & cáp USB‑C", "Sổ tay hướng dẫn song ngữ", "Bộ thẻ tình huống 100 thẻ"],
      },
      {
        slug: "halabuddy-pro",
        name: "HalaBuddy Pro",
        category: "education",
        art: "pro",
        tint: "blue",
        tagline: "Robot gia sư tiếng Anh có màn hình & camera",
        price: 3990000,
        compareAtPrice: 4490000,
        rating: 4.9,
        sold: 860,
        freeShipping: true,
        ages: ["9-15"],
        ageLabel: "9 – 15 tuổi",
        colors: [
          { id: "white", name: "Trắng", hex: "#f4f4f4" },
          { id: "black", name: "Đen", hex: "#1a1a1a" },
        ],
        badge: "Cao cấp",
        audience: "Học sinh 9 – 15 tuổi, luyện thi KET/PET, IELTS Junior",
        summary:
          "Phiên bản cao cấp với màn hình cảm ứng 5 inch và camera: học theo hình ảnh, luyện thuyết trình, chấm bài viết và bài nói theo chuẩn thi quốc tế.",
        highlights: [
          "Màn hình 5\" cảm ứng, camera nhận diện sách và thẻ",
          "Luyện thi KET, PET, IELTS Junior — Speaking & Writing",
          "Luyện thuyết trình, ghi hình và nhận xét",
          "Tài khoản cho 3 học sinh trong gia đình",
        ],
        features: [
          { title: "Học qua hình ảnh", body: "Đưa sách, đồ vật trước camera — robot gọi tên, đặt câu và hỏi lại con bằng tiếng Anh." },
          { title: "Chấm Speaking theo chuẩn", body: "Mô phỏng phần thi nói KET/PET/IELTS Junior, chấm theo tiêu chí phát âm, từ vựng, ngữ pháp, lưu loát." },
          { title: "Chấm Writing", body: "Chụp bài viết tay — robot nhận diện, sửa lỗi và gợi ý cách viết hay hơn." },
          { title: "Luyện thuyết trình", body: "Ghi hình bài thuyết trình, nhận xét về tốc độ, ngữ điệu và ngôn ngữ cơ thể." },
          { title: "Hồ sơ nhiều con", body: "Tối đa 3 hồ sơ học sinh, mỗi hồ sơ có lộ trình và báo cáo riêng." },
        ],
        specs: [
          { label: "Kích thước", value: "22 × 14 × 14 cm · 900 g" },
          { label: "Màn hình", value: "5\" IPS cảm ứng" },
          { label: "Camera", value: "8 MP, có nắp che vật lý" },
          { label: "Pin", value: "8 giờ, sạc USB‑C 20 W" },
          { label: "Kết nối", value: "Wi‑Fi 2.4/5 GHz, Bluetooth 5.2" },
          { label: "Âm thanh", value: "2 loa 5 W, 4 micro định hướng" },
        ],
        inBox: ["Robot HalaBuddy Pro", "Đế sạc & củ sạc 20 W", "Sổ tay hướng dẫn song ngữ", "Bộ thẻ hình ảnh 120 thẻ", "Túi đựng"],
      },
      {
        slug: "halahome",
        name: "HalaHome",
        category: "home",
        art: "home",
        tint: "green",
        tagline: "Trợ lý AI cho cả gia đình",
        price: 3490000,
        rating: 4.7,
        sold: 540,
        freeShipping: true,
        ages: ["family"],
        ageLabel: "Cả gia đình",
        badge: "Mới",
        audience: "Gia đình có trẻ nhỏ và người lớn tuổi",
        summary:
          "Robot trợ lý đặt ở phòng khách: nhắc lịch cho cả nhà, đọc tin thời tiết, đặt báo thức, gọi video cho người thân, điều khiển thiết bị và trò chuyện bằng tiếng Việt lẫn tiếng Anh.",
        highlights: [
          "Nhắc lịch, nhắc việc cho từng thành viên",
          "Gọi video người thân bằng giọng nói",
          "Điều khiển đèn, quạt, TV tương thích",
          "Trò chuyện song ngữ Việt – Anh",
        ],
        features: [
          { title: "Lịch gia đình", body: "Lịch học của con, lịch khám của ông bà, lịch họp của bố mẹ — robot nhắc đúng người, đúng giờ." },
          { title: "Gọi video một câu nói", body: "\"Gọi cho mẹ\" — màn hình xoay về phía người nói và kết nối qua ứng dụng TechHala." },
          { title: "Nhà thông minh", body: "Điều khiển đèn, quạt, TV và các thiết bị thông minh tương thích bằng tiếng Việt." },
          { title: "Chế độ trẻ em", body: "Khi con dùng, robot tự chuyển sang nội dung học tiếng Anh như dòng HalaBuddy." },
        ],
        specs: [
          { label: "Kích thước", value: "24 × 16 × 16 cm · 1,1 kg" },
          { label: "Màn hình", value: "7\" IPS cảm ứng, xoay 180°" },
          { label: "Camera", value: "5 MP, nắp che vật lý" },
          { label: "Nguồn", value: "Adapter 12 V, pin dự phòng 2 giờ" },
          { label: "Kết nối", value: "Wi‑Fi 2.4/5 GHz, Bluetooth 5.2, hồng ngoại" },
          { label: "Âm thanh", value: "2 loa 8 W, 6 micro" },
        ],
        inBox: ["Robot HalaHome", "Adapter 12 V", "Sổ tay hướng dẫn", "Thẻ cài đặt nhanh"],
      },
      {
        slug: "halacare",
        name: "HalaCare",
        category: "home",
        art: "care",
        tint: "purple",
        tagline: "Robot đồng hành cho ông bà",
        price: 2690000,
        compareAtPrice: 2990000,
        rating: 4.8,
        sold: 910,
        freeShipping: true,
        ages: ["seniors"],
        ageLabel: "Ông bà",
        badge: "Cho người lớn tuổi",
        audience: "Người lớn tuổi sống một mình hoặc ở nhà ban ngày",
        summary:
          "Robot nhỏ gọn, nút bấm lớn, giọng nói rõ: nhắc uống thuốc, đọc báo, kể chuyện, nghe nhạc, gọi nhanh con cháu và trò chuyện suốt ngày bằng tiếng Việt.",
        highlights: [
          "Nhắc thuốc theo lịch, xác nhận đã uống",
          "Gọi nhanh người thân bằng một nút hoặc một câu nói",
          "Đọc báo, kể chuyện, nghe nhạc, radio",
          "Ứng dụng cho con cháu theo dõi hoạt động trong ngày",
        ],
        features: [
          { title: "Nhắc thuốc thông minh", body: "Nhắc đúng giờ, hỏi lại đã uống chưa và báo cho người thân nếu bỏ lỡ." },
          { title: "Kết nối con cháu", body: "Gọi thoại/video tới số đã cài, nhận tin nhắn thoại từ ứng dụng TechHala." },
          { title: "Trò chuyện thân thiện", body: "Giọng nói tiếng Việt tự nhiên, kiên nhẫn, hỏi thăm và nhắc vận động nhẹ mỗi ngày." },
          { title: "Đơn giản tối đa", body: "Ba nút bấm lớn, âm lượng to, không cần chạm màn hình." },
        ],
        specs: [
          { label: "Kích thước", value: "16 × 12 × 12 cm · 600 g" },
          { label: "Pin", value: "12 giờ, sạc trên đế" },
          { label: "Kết nối", value: "Wi‑Fi 2.4 GHz, Bluetooth 5.0" },
          { label: "Âm thanh", value: "Loa 5 W âm lượng lớn, 2 micro" },
          { label: "Ứng dụng", value: "TechHala Family (iOS/Android)" },
        ],
        inBox: ["Robot HalaCare", "Đế sạc", "Sổ tay hướng dẫn chữ lớn", "Thẻ cài đặt nhanh"],
      },
      {
        slug: "combo-anh-em",
        name: "Combo Anh Em — 2 × HalaBuddy Mini",
        category: "combo",
        art: "combo-siblings",
        tint: "peach",
        tagline: "Hai bé cùng học, hai robot cùng chơi với nhau",
        price: 4290000,
        compareAtPrice: 4580000,
        rating: 4.9,
        sold: 210,
        freeShipping: true,
        ages: ["4-8"],
        ageLabel: "4 – 8 tuổi",
        badge: "Tiết kiệm 290K",
        audience: "Gia đình có 2 bé 4 – 8 tuổi",
        summary:
          "Hai robot HalaBuddy Mini (tự chọn màu) kết nối được với nhau: các bé thi đoán từ, hát đối đáp và đóng vai hội thoại. Mỗi bé một hồ sơ và báo cáo riêng.",
        highlights: ["2 robot HalaBuddy Mini, tự chọn màu", "Chế độ chơi đôi: thi đoán từ, hát đối đáp", "2 hồ sơ học sinh riêng", "Tặng 2 bộ thẻ từ vựng 50 thẻ"],
        features: [
          { title: "Chơi đôi", body: "Hai robot nhận ra nhau qua Wi‑Fi, mở trò chơi đố từ và hội thoại đóng vai giữa hai bé." },
          { title: "Hồ sơ riêng", body: "Mỗi bé có lộ trình, huy hiệu và báo cáo riêng trong cùng một ứng dụng phụ huynh." },
        ],
        specs: [
          { label: "Gồm", value: "2 × HalaBuddy Mini" },
          { label: "Màu", value: "Chọn khi đặt hàng (ghi chú)" },
          { label: "Bảo hành", value: "12 tháng / robot" },
        ],
        inBox: ["2 robot HalaBuddy Mini", "2 cáp sạc USB‑C", "2 bộ thẻ từ vựng 50 thẻ", "Sổ tay hướng dẫn"],
      },
      {
        slug: "combo-hoc-tap",
        name: "Combo Học Tập — HalaBuddy + Đế sạc + 200 thẻ",
        category: "combo",
        art: "combo-study",
        tint: "yellow",
        tagline: "Trọn bộ cho học sinh tiểu học – THCS",
        price: 3290000,
        compareAtPrice: 3428000,
        rating: 4.9,
        sold: 480,
        freeShipping: true,
        ages: ["6-12", "9-15"],
        ageLabel: "6 – 15 tuổi",
        badge: "Combo được chọn nhiều",
        audience: "Học sinh 6 – 15 tuổi muốn học đều mỗi ngày",
        summary:
          "Robot HalaBuddy kèm đế sạc để luôn sẵn sàng trên bàn học và bộ 200 thẻ từ vựng theo chủ đề — robot nhận diện thẻ qua giọng đọc của con.",
        highlights: ["HalaBuddy bản đầy đủ", "Đế sạc để bàn", "200 thẻ từ vựng 12 chủ đề", "Tiết kiệm so với mua lẻ"],
        features: [
          { title: "Luôn sẵn sàng", body: "Đế sạc giữ robot đầy pin trên bàn học, chỉ cần gọi “Hey Hala” để bắt đầu." },
          { title: "Học với thẻ", body: "Con đọc từ trên thẻ, robot chấm phát âm và đặt câu ví dụ." },
        ],
        specs: [
          { label: "Gồm", value: "HalaBuddy + Đế sạc + Bộ 200 thẻ" },
          { label: "Màu robot", value: "Trắng / Đỏ / Xanh (ghi chú khi đặt)" },
        ],
        inBox: ["Robot HalaBuddy", "Đế sạc để bàn", "Bộ 200 thẻ từ vựng", "Sổ tay hướng dẫn"],
      },
      {
        slug: "combo-gia-dinh",
        name: "Combo Gia Đình — HalaHome + HalaCare",
        category: "combo",
        art: "combo-family",
        tint: "green",
        tagline: "Trợ lý phòng khách + bạn đồng hành cho ông bà",
        price: 5790000,
        compareAtPrice: 6180000,
        rating: 4.8,
        sold: 120,
        freeShipping: true,
        ages: ["family", "seniors"],
        ageLabel: "Cả nhà",
        badge: "Tiết kiệm 390K",
        audience: "Gia đình nhiều thế hệ",
        summary:
          "HalaHome ở phòng khách, HalaCare ở phòng ông bà — hai robot đồng bộ lịch nhắc thuốc, gọi nội bộ giữa các phòng và báo cho con cháu khi cần.",
        highlights: ["HalaHome + HalaCare", "Gọi nội bộ giữa hai phòng", "Đồng bộ lịch cả nhà", "Tiết kiệm 390.000đ"],
        features: [
          { title: "Gọi nội bộ", body: "“Gọi bà” từ phòng khách — HalaCare đổ chuông ngay trong phòng ông bà." },
          { title: "Một ứng dụng", body: "Cả hai robot quản lý trong ứng dụng TechHala Family." },
        ],
        specs: [{ label: "Gồm", value: "HalaHome + HalaCare" }],
        inBox: ["Robot HalaHome + adapter", "Robot HalaCare + đế sạc", "Sổ tay hướng dẫn"],
      },
      {
        slug: "de-sac-halabuddy",
        name: "Đế sạc để bàn HalaBuddy",
        category: "accessory",
        art: "dock",
        tint: "blue",
        tagline: "Sạc nhanh, để bàn gọn gàng",
        price: 290000,
        rating: 4.7,
        sold: 1560,
        freeShipping: true,
        ages: [],
        audience: "Dùng cho HalaBuddy Mini, HalaBuddy, HalaBuddy Pro",
        summary: "Đế sạc tiếp điểm, đặt robot lên là sạc. Đèn báo pin, chống trượt, dây USB‑C 1,5 m.",
        highlights: ["Sạc tiếp điểm, không cần cắm dây", "Đèn báo pin", "Đế chống trượt"],
        features: [{ title: "Tương thích", body: "Toàn bộ dòng HalaBuddy (Mini, tiêu chuẩn, Pro)." }],
        specs: [
          { label: "Công suất", value: "15 W" },
          { label: "Cáp", value: "USB‑C 1,5 m" },
        ],
        inBox: ["Đế sạc", "Cáp USB‑C"],
      },
      {
        slug: "op-silicone-halabuddy",
        name: "Ốp silicone HalaBuddy",
        category: "accessory",
        art: "case",
        tint: "pink",
        tagline: "Chống va đập, 4 màu",
        price: 190000,
        rating: 4.6,
        sold: 2030,
        freeShipping: true,
        ages: ["4-8", "6-12"],
        colors: [
          { id: "pink", name: "Hồng", hex: "#ff8fa3" },
          { id: "mint", name: "Xanh mint", hex: "#7fd8c8" },
          { id: "yellow", name: "Vàng", hex: "#ffd166" },
          { id: "purple", name: "Tím", hex: "#b39ddb" },
        ],
        audience: "HalaBuddy Mini và HalaBuddy",
        summary: "Ốp silicone mềm, chịu va đập khi bé làm rơi, không che loa và micro. An toàn cho trẻ, rửa được.",
        highlights: ["Silicone mềm an toàn cho trẻ", "Không che loa/micro", "4 màu"],
        features: [{ title: "Bảo vệ", body: "Giảm va đập khi rơi từ độ cao 1 m." }],
        specs: [{ label: "Chất liệu", value: "Silicone thực phẩm" }],
        inBox: ["Ốp silicone"],
      },
      {
        slug: "bo-the-tu-vung-200",
        name: "Bộ 200 thẻ từ vựng",
        category: "accessory",
        art: "cards",
        tint: "yellow",
        tagline: "12 chủ đề, robot nhận diện qua giọng đọc",
        price: 149000,
        rating: 4.8,
        sold: 2870,
        freeShipping: true,
        ages: ["4-8", "6-12"],
        audience: "Trẻ 4 – 12 tuổi",
        summary: "200 thẻ cứng in hai mặt: hình – từ – phiên âm. Con đọc từ, robot chấm phát âm và đặt câu ví dụ.",
        highlights: ["200 thẻ, 12 chủ đề", "Giấy cứng, bọc bóng", "Có phiên âm IPA"],
        features: [{ title: "Học cùng robot", body: "Chế độ Flashcard trên HalaBuddy nhận ra từ con đọc và phản hồi ngay." }],
        specs: [{ label: "Kích thước thẻ", value: "9 × 6 cm" }],
        inBox: ["200 thẻ", "Hộp đựng"],
      },
      {
        slug: "tui-dung-halabuddy",
        name: "Túi đựng HalaBuddy",
        category: "accessory",
        art: "bag",
        tint: "purple",
        tagline: "Mang robot đi học, đi du lịch",
        price: 249000,
        rating: 4.7,
        sold: 640,
        freeShipping: true,
        ages: [],
        audience: "HalaBuddy Mini, HalaBuddy, HalaBuddy Pro",
        summary: "Túi chống sốc có ngăn phụ kiện, dây đeo, khóa kéo êm. Vừa cả robot và đế sạc.",
        highlights: ["Chống sốc", "Ngăn phụ kiện", "Dây đeo tháo rời"],
        features: [{ title: "Gọn nhẹ", body: "Chỉ 180 g, vừa HalaBuddy Pro và đế sạc." }],
        specs: [{ label: "Kích thước", value: "26 × 18 × 16 cm" }],
        inBox: ["Túi đựng", "Dây đeo"],
      },
      {
        slug: "goi-premium-12-thang",
        name: "Gói nội dung Premium 12 tháng",
        category: "accessory",
        art: "premium",
        tint: "peach",
        tagline: "Thêm 1.000+ bài học, đề luyện thi & báo cáo chi tiết",
        price: 599000,
        rating: 4.8,
        sold: 1180,
        freeShipping: true,
        ages: ["6-12", "9-15"],
        badge: "Kích hoạt online",
        audience: "HalaBuddy, HalaBuddy Pro (không bắt buộc)",
        summary:
          "Robot vẫn dùng đầy đủ không cần gói này. Premium bổ sung kho bài học mở rộng, đề luyện thi Cambridge đầy đủ và báo cáo phát âm chi tiết từng âm.",
        highlights: ["1.000+ bài học mở rộng", "Trọn bộ đề Starters – PET", "Báo cáo phát âm theo âm", "Mã kích hoạt gửi qua SMS/Zalo"],
        features: [{ title: "Không bắt buộc", body: "Giá robot đã gồm toàn bộ bài học cơ bản; Premium là tùy chọn cho bé học nhanh." }],
        specs: [{ label: "Thời hạn", value: "12 tháng từ ngày kích hoạt" }],
        inBox: ["Mã kích hoạt (gửi qua SMS/Zalo/email)"],
      },
    ],
  },
  checkout: {
    title: "Đặt hàng",
    subtitle: "Điền thông tin giao hàng, chúng tôi sẽ gọi xác nhận trong vòng 2 giờ làm việc.",
    noProduct: "Giỏ hàng của bạn đang trống.",
    chooseProduct: "Chọn sản phẩm",
    addMore: "Thêm sản phẩm",
    summary: "Đơn hàng của bạn",
    quantity: "Số lượng",
    shipping: "Phí giao hàng",
    total: "Tổng cộng",
    form: {
      name: "Họ và tên",
      phone: "Số điện thoại",
      email: "Email (không bắt buộc)",
      address: "Địa chỉ nhận hàng",
      note: "Ghi chú (tuổi của con, thời gian nhận hàng…)",
      payment: "Phương thức thanh toán",
      submit: "Xác nhận đặt hàng",
      sending: "Đang gửi…",
    },
    payments: [
      { id: "cod", name: "Thanh toán khi nhận hàng (COD)", body: "Kiểm tra hàng rồi mới thanh toán cho nhân viên giao hàng.", available: true },
      { id: "bank", name: "Chuyển khoản ngân hàng", body: "Nhân viên gọi xác nhận đơn và gửi thông tin tài khoản để bạn chuyển khoản.", available: true },
      { id: "online", name: "Thanh toán online (MoMo, VNPay, thẻ)", body: "Sắp ra mắt.", available: false },
    ],
    success: {
      title: "Đã nhận đơn hàng!",
      body: "Cảm ơn bạn. TechHala sẽ gọi xác nhận đơn hàng trong vòng 2 giờ làm việc.",
      orderCode: "Mã đơn hàng",
      next: [
        "Nhân viên gọi xác nhận địa chỉ và thời gian giao hàng.",
        "Nếu chọn chuyển khoản, bạn sẽ nhận thông tin tài khoản qua SMS/Zalo.",
        "Giao hàng trong 2 – 4 ngày làm việc, kiểm tra hàng trước khi thanh toán.",
      ],
      track: "Theo dõi đơn hàng",
    },
    error: "Không gửi được đơn hàng. Vui lòng gọi hotline hoặc thử lại.",
    support: { title: "Cần hỗ trợ đặt hàng?", body: "Gọi hotline hoặc nhắn Zalo, chúng tôi đặt hàng thay bạn trong 2 phút." },
  },
  orders: {
    title: "Tra cứu đơn hàng",
    subtitle: "Nhập mã đơn hàng trong thông báo xác nhận và số điện thoại bạn đã dùng khi đặt hàng.",
    form: {
      code: "Mã đơn hàng",
      phone: "Số điện thoại",
      submit: "Tra cứu",
      searching: "Đang tra cứu…",
      notFound: "Không tìm thấy đơn hàng khớp mã và số điện thoại này. Vui lòng kiểm tra lại hoặc gọi hotline.",
    },
    detail: {
      title: "Đơn hàng",
      placedAt: "Đặt lúc",
      status: "Trạng thái",
      payment: "Thanh toán",
      paymentStatus: "Tình trạng thanh toán",
      items: "Sản phẩm",
      total: "Tổng cộng",
      shipTo: "Giao đến",
      note: "Ghi chú của bạn",
      history: "Lịch sử",
      help: "Có thắc mắc về đơn hàng? Gọi hoặc nhắn Zalo cho chúng tôi kèm mã đơn hàng.",
      bankTitle: "Chuyển khoản ngân hàng",
      bankBody: "Chúng tôi sẽ gọi xác nhận đơn và gửi thông tin tài khoản qua SMS/Zalo. Khi chuyển khoản, bạn vui lòng ghi nội dung như bên dưới.",
      transferNote: "Nội dung chuyển khoản",
      lookupAnother: "Tra cứu đơn khác",
    },
    statuses: {
      pending: "Đã nhận — chờ xác nhận",
      confirmed: "Đã xác nhận",
      packed: "Đã đóng gói",
      shipping: "Đang giao",
      delivered: "Đã giao",
      cancelled: "Đã huỷ",
      returned: "Đã hoàn trả",
    },
    paymentMethods: { cod: "Thanh toán khi nhận hàng (COD)", bank: "Chuyển khoản ngân hàng" },
    paymentStatuses: { unpaid: "Chưa thanh toán", paid: "Đã thanh toán", refunded: "Đã hoàn tiền" },
  },
  solutions: {
    title: "Giải pháp AI cho doanh nghiệp",
    subtitle:
      "Bên cạnh robot AI cho gia đình, TechHala triển khai AI cho đội ngũ phần mềm và doanh nghiệp: HAL‑SDLC cho phát triển phần mềm bằng AI, chatbot & trợ lý AI nội bộ, và vận hành hệ thống AI (AIOps).",
    sectionLabels: {
      problem: "Vấn đề",
      approach: "Cách tiếp cận",
      capabilities: "Năng lực",
      outcomes: "Kết quả",
      useCases: "Trường hợp ứng dụng",
    },
    relatedWork: "Dự án liên quan",
    flagship: {
      eyebrow: "Nền tảng",
      title: "HAL‑SDLC — AI cho vòng đời phát triển phần mềm",
      body: "Mô tả điều bạn muốn bằng ngôn ngữ tự nhiên. HAL lập kế hoạch, điều phối các agent xây dựng, review đối kháng và mở pull request với nhật ký kiểm toán đầy đủ — triển khai trong môi trường của bạn.",
      cta: "Xem HAL‑SDLC",
    },
    cta: {
      title: "Có hệ thống cần xây — hoặc cần vận hành?",
      body: "Kể cho chúng tôi nghe. Bạn sẽ nhận lại một cách tiếp cận cụ thể, không phải một bộ slide.",
      button: "Trao đổi với chúng tôi",
    },
    items: [
      {
        slug: "ai-robot",
        name: "AI Robot",
        tagline: "Robot thông minh biết dạy, biết trò chuyện và học cùng con người.",
        summary:
          "Chúng tôi xây dựng lớp trí tuệ cho robot giáo dục và robot dịch vụ: hội thoại tự nhiên, giọng nói và thị giác, gia sư thích ứng — bắt đầu với robot giúp trẻ em và người lớn học tiếng Anh.",
        problem: {
          title: "Robot biết di chuyển. Rất ít robot biết trò chuyện có ý nghĩa.",
          body:
            "Phần lớn robot giáo dục chạy các hội thoại kịch bản mà trẻ chán chỉ sau một tuần, còn người học ngoại ngữ hiếm khi có đủ cơ hội luyện nói với một người bạn kiên nhẫn. Phần cứng đã có — điều còn thiếu là trí tuệ biết lắng nghe, hiểu, thích ứng với từng người học và an toàn cho lớp học lẫn gia đình.",
        },
        approach: {
          title: "Lắng nghe, hiểu, dạy, thích ứng",
          steps: [
            { title: "Hội thoại tự nhiên", body: "Giọng nói sang giọng nói độ trễ thấp với tính cách nhất quán, để robot giống một người bạn đồng hành, không phải một menu." },
            { title: "Sư phạm tích hợp", body: "Giáo án, lộ trình từ vựng, phản hồi phát âm và trò chơi được thiết kế cùng giáo viên, bám theo khung CEFR." },
            { title: "Nhận thức & hiện diện", body: "Thị giác và giọng nói giúp robot nhận ra người học, đọc mức độ tập trung và phản hồi bằng biểu cảm, cử chỉ." },
            { title: "Học từ mỗi buổi", body: "Theo dõi tiến độ cho giáo viên và phụ huynh; gia sư điều chỉnh độ khó và chủ đề theo từng người học." },
          ],
        },
        capabilities: [
          { title: "Bạn đồng hành học tiếng Anh", body: "Luyện hội thoại, sửa phát âm, trò chơi từ vựng và kể chuyện — tối ưu cho trẻ em và người học trưởng thành." },
          { title: "Bộ não hội thoại", body: "Nhận dạng giọng nói, suy luận LLM có rào chắn và tổng hợp giọng nói biểu cảm — chạy trên thiết bị hoặc hybrid." },
          { title: "Thị giác & tương tác", body: "Nhận dạng khuôn mặt, cử chỉ, tín hiệu tập trung và nhận dạng vật thể cho bài học tương tác." },
          { title: "Bảng điều khiển giáo viên & phụ huynh", body: "Tóm tắt buổi học, tiến độ theo kỹ năng và kiểm soát nội dung." },
          { title: "Tích hợp robot & phần cứng", body: "Tích hợp với robot hình người, robot để bàn và robot di động — chuyển động, LED, màn hình và cảm biến." },
          { title: "An toàn & riêng tư", body: "Bộ lọc nội dung theo độ tuổi, xử lý trên thiết bị khi có thể và quy trình đồng ý của phụ huynh." },
        ],
        outcomes: [
          "Nhiều thời gian luyện nói cho mỗi người học hơn bất kỳ lớp học nào",
          "Sự hứng thú kéo dài sau tuần đầu tò mò",
          "Tiến độ đo lường được cho giáo viên và phụ huynh",
          "Một nền tảng trí tuệ dùng chung cho nhiều mẫu robot",
        ],
        useCases: [
          "Robot học tiếng Anh cho trường mầm non và tiểu học",
          "Bạn đồng hành gia sư tại nhà cho trẻ em",
          "Trung tâm ngoại ngữ và kiosk tự học",
          "Robot lễ tân, bảo tàng và dịch vụ trò chuyện tự nhiên",
        ],
        cta: "Trao đổi về dự án robot giáo dục",
      },
      {
        slug: "ai-sdlc",
        name: "AI cho SDLC",
        tagline: "Biến ý định kinh doanh thành phần mềm truy vết được, đã review, chạy thật.",
        summary:
          "Vòng đời phát triển phần mềm dẫn dắt bởi AI: lập kế hoạch, xây dựng, kiểm chứng và phát hành với các agent chuyên biệt — con người vẫn kiểm soát mọi quyết định. Vận hành trên nền tảng HAL-SDLC của chúng tôi.",
        problem: {
          title: "Trợ lý viết mã giúp gõ nhanh hơn. Nhưng không giúp bàn giao nhanh hơn.",
          body:
            "Các đội ngũ dùng công cụ AI viết mã thấy đoạn mã ra nhanh hơn nhưng vẫn gặp nút thắt cũ: yêu cầu không rõ, đầu ra không được review, chuẩn không đồng nhất, và không có hồ sơ lý do vì sao thứ đó được xây. Kết quả: nhiều mã hơn, ít tự tin hơn.",
        },
        approach: {
          title: "Vòng đời trước, mã nguồn sau",
          steps: [
            {
              title: "Lập kế hoạch có cấu trúc",
              body: "Ý định kinh doanh trở thành kế hoạch với tiêu chí chấp nhận, ghi chú kiến trúc và đồ thị phụ thuộc — có thể review trước khi có bất kỳ dòng mã nào.",
            },
            {
              title: "Xây dựng có điều phối",
              body: "Các agent chuyên biệt triển khai song song theo giai đoạn, dựa trên quy ước, tài liệu và các quyết định trước đây của bạn.",
            },
            {
              title: "Kiểm chứng độc lập",
              body: "Agent review riêng biệt chấm điểm mọi sản phẩm về tính đúng, chất lượng, bảo mật và kiểm thử. Không có gì được merge chỉ dựa trên niềm tin.",
            },
            {
              title: "Học hỏi liên tục",
              body: "Mỗi vòng lặp ghi lại bài học vào lớp tri thức, để kế hoạch tiếp theo tốt hơn kế hoạch trước.",
            },
          ],
        },
        capabilities: [
          { title: "Nền tảng HAL-SDLC", body: "Engine của chúng tôi cho lập kế hoạch, thực thi và review bằng AI — triển khai trong môi trường của bạn." },
          { title: "Trang bị cho agent", body: "Kỹ năng, quy tắc và ngữ cảnh để agent tuân theo kiến trúc và chuẩn của bạn." },
          { title: "Lớp tri thức", body: "Tài liệu, ADR và mã nguồn của bạn được chưng cất thành wiki tra cứu được mà agent thực sự dùng." },
          { title: "Cổng chất lượng", body: "Review đa persona, kiểm toán bảo mật, sinh kiểm thử và hoàn thiện trước phát hành." },
          { title: "Tích hợp IDE & MCP", body: "Hoạt động với Cursor và mọi công cụ tương thích MCP mà lập trình viên đang dùng." },
          { title: "Chương trình triển khai", body: "Thí điểm, đo lường và mở rộng ra các đội ngũ với quản trị rõ ràng." },
        ],
        outcomes: [
          "Chu kỳ từ ý tưởng đến PR nhanh hơn, ít vòng review hơn",
          "Chuẩn đồng nhất giữa các đội ngũ và repository",
          "Nhật ký kiểm toán đầy đủ cho mọi thay đổi do AI tạo ra",
          "Lập trình viên tập trung vào phán đoán, không phải mã lặp",
        ],
        useCases: [
          "Hiện đại hóa nền tảng cũ theo từng module",
          "Xây dựng công cụ nội bộ và cổng khách hàng nhanh chóng",
          "Tăng năng suất kỹ thuật mà không tăng nhân sự",
          "Môi trường có quy định chặt cần truy vết",
        ],
        cta: "Trao đổi về thí điểm AI SDLC",
      },
      {
        slug: "ai-enterprise",
        name: "AI cho Doanh nghiệp",
        tagline: "Chatbot, trợ lý và dịch vụ AI triển khai an toàn trong tổ chức của bạn.",
        summary:
          "Từ chatbot phục vụ khách hàng đến copilot nội bộ và nền tảng AI riêng — chúng tôi thiết kế, xây dựng, triển khai và vận hành các dịch vụ AI phù hợp với dữ liệu, hệ thống và yêu cầu tuân thủ của bạn.",
        problem: {
          title: "Làm demo mất một ngày. Đưa dịch vụ AI vào vận hành cần kỷ luật.",
          body:
            "Tạo nguyên mẫu với mô hình ngôn ngữ lớn rất dễ. Dịch vụ doanh nghiệp đáng tin cậy — bám vào dữ liệu của bạn, tích hợp với hệ thống, bảo mật, được đánh giá, kiểm soát chi phí và giám sát trong production — là nơi hầu hết sáng kiến bị mắc kẹt.",
        },
        approach: {
          title: "Từ bài toán đến dịch vụ đang chạy",
          steps: [
            { title: "Khám phá", body: "Xác định các trường hợp giá trị nhất, nguồn dữ liệu và chỉ số thành công cùng đội kinh doanh và CNTT." },
            { title: "Thiết kế", body: "Thiết kế hội thoại, kiến trúc tri thức và bản thiết kế tích hợp phù hợp bảo mật và tuân thủ." },
            { title: "Xây dựng & tích hợp", body: "Truy xuất, điều phối, rào chắn và kết nối với CRM, ERP, hệ thống ticket và định danh." },
            { title: "Triển khai & vận hành", body: "Triển khai riêng hoặc hybrid, giám sát, quản lý chi phí, đánh giá và cải tiến liên tục." },
          ],
        },
        capabilities: [
          { title: "Chatbot chăm sóc khách hàng", body: "Trợ lý đa ngôn ngữ cho web, ứng dụng và kênh nhắn tin — bám vào tri thức của bạn, có chuyển tiếp cho nhân viên." },
          { title: "Trợ lý & copilot cho nhân viên", body: "Copilot nội bộ cho nhân sự, CNTT, kinh doanh và vận hành: trả lời từ chính sách và thao tác trong công cụ của bạn." },
          { title: "Trung tâm tri thức & RAG", body: "Tài liệu, cơ sở dữ liệu và ticket biến thành câu trả lời tin cậy có trích dẫn và phân quyền." },
          { title: "Nền tảng AI riêng", body: "LLM gateway, lưu trữ mô hình và hạ tầng vector triển khai trên cloud của bạn hoặc tại chỗ." },
          { title: "Vận hành dịch vụ AI", body: "Giám sát, đánh giá, kiểm soát chi phí và xử lý sự cố cho AI trong production — bao gồm AIOps cho nền tảng của bạn." },
          { title: "Nội dung sinh tạo & sản phẩm dữ liệu", body: "Pipeline sinh ảnh, video, tài liệu và các ứng dụng giàu dữ liệu được xây cho quy mô lớn." },
        ],
        outcomes: [
          "Trợ lý giải quyết yêu cầu, không chỉ né tránh",
          "Câu trả lời bám vào dữ liệu của bạn, có nguồn và tôn trọng phân quyền",
          "Chi phí dự đoán được và chất lượng đo lường được sau khi ra mắt",
          "Nền tảng bạn sở hữu — không phụ thuộc nhà cung cấp",
        ],
        useCases: [
          "Trợ lý hỗ trợ khách hàng và bán hàng cho bán lẻ, ngân hàng, viễn thông",
          "Trợ lý tri thức nội bộ cho tổ chức lớn",
          "Triển khai dịch vụ LLM riêng cho ngành có quy định chặt",
          "Nền tảng nội dung, truyền thông và dữ liệu vận hành bằng AI sinh tạo",
        ],
        cta: "Trao đổi về dự án AI doanh nghiệp",
      },
    ],
  },
  product: {
    eyebrow: "Sản phẩm",
    title: "HAL-SDLC",
    subtitle:
      "Vòng đời AI heuristic cho phát triển phần mềm. Mô tả ý định bằng ngôn ngữ tự nhiên — HAL lập kế hoạch, điều phối các agent chuyên biệt, review đối kháng và phát hành với nhật ký kiểm toán đầy đủ. Triển khai riêng, trong môi trường của bạn.",
    primaryCta: "Yêu cầu demo riêng",
    secondaryCta: "Khám phá cách tiếp cận AI SDLC",
    terminal: [
      {
        cmd: 'hal plan "Cổng khách hàng với SSO và dashboard sử dụng"',
        out: [
          "✓ Chọn mẫu: fullstack-feature",
          "✓ 6 sub-PRP, 3 giai đoạn thực thi, đã giải DAG",
          "✓ Đã viết ghi chú kiến trúc + tiêu chí chấp nhận",
        ],
      },
      {
        cmd: "hal execute",
        out: [
          "→ Giai đoạn 1/3: auth-service, schema  (2 agent)",
          "→ Giai đoạn 2/3: api, dashboard-ui     (2 agent)",
          "→ Giai đoạn 3/3: e2e-tests             (1 agent)",
        ],
      },
      {
        cmd: "hal review",
        out: [
          "10 persona · 0 P0 · 1 P2 đã tự sửa",
          "Điểm 91/100 — ĐƯỢC DUYỆT",
          "✓ Đã mở pull request với đầy đủ nhật ký kiểm toán",
        ],
      },
    ],
    stats: [
      { value: "35+", label: "lệnh CLI" },
      { value: "10", label: "persona review" },
      { value: "8", label: "mẫu chuyên biệt" },
      { value: "100%", label: "quyết định truy vết được" },
    ],
    workflow: {
      title: "Cách hoạt động",
      steps: [
        { name: "Lập kế hoạch", desc: "Một câu ý định trở thành bộ kế hoạch có cấu trúc: chỉ mục, tác vụ con, ghi chú kiến trúc, tiêu chí chấp nhận và đồ thị phụ thuộc." },
        { name: "Kiểm tra", desc: "Các cổng cấu trúc chấm điểm kế hoạch trước khi ai đó viết mã. Lỗi ở tầng kế hoạch được sửa khi còn rẻ nhất." },
        { name: "Thực thi", desc: "Agent triển khai song song theo giai đoạn — kỹ sư, reviewer và planner mỗi vai trò được định nghĩa rõ." },
        { name: "Review", desc: "Reviewer độc lập với 10 persona chấm điểm mọi sản phẩm theo mức độ nghiêm trọng và độ tin cậy. Tự sửa có giới hạn xử lý các lỗi nhỏ." },
        { name: "Phát hành", desc: "Commit chuẩn, pull request và nhật ký quyết định đầy đủ — sẵn sàng cho con người phê duyệt." },
        { name: "Tích lũy", desc: "Bài học được ghi vào lớp tri thức để vòng tiếp theo bắt đầu thông minh hơn." },
      ],
    },
    features: {
      title: "Điểm khác biệt",
      items: [
        { title: "Kế hoạch đội ngũ có thể review", body: "Mọi lần xây dựng bắt đầu từ đặc tả với tiêu chí chấp nhận và bằng chứng rõ ràng — không phải từ một đoạn chat." },
        { title: "Điều phối đa agent", body: "Các giai đoạn nhận biết phụ thuộc phân công cho agent chuyên biệt và giữ chúng phối hợp." },
        { title: "Review đối kháng", body: "Các persona kiến trúc, bảo mật, hiệu năng và đối kháng review độc lập. Phát hiện kèm mức độ nghiêm trọng và độ tin cậy." },
        { title: "Tri thức ba lớp", body: "Tài liệu của bạn được chưng cất và biên dịch thành wiki liên kết mà agent tra cứu trước khi xây dựng." },
        { title: "Chế độ solo và full", body: "Luồng nhẹ cho tác vụ một lập trình viên; điều phối đầy đủ cho công việc đa dịch vụ. Cùng một chuẩn chất lượng." },
        { title: "Riêng tư mặc định", body: "Chạy trong môi trường của bạn. Tên và thuật ngữ nhạy cảm được tự động ẩn khỏi sản phẩm sinh ra." },
      ],
    },
    audiences: {
      title: "Dành cho ai",
      items: [
        { title: "Lãnh đạo kỹ thuật", body: "Mở rộng năng lực bàn giao với quản trị, chuẩn và khả năng quan sát tích hợp sẵn." },
        { title: "Đội Platform & DevEx", body: "Cung cấp cho mọi lập trình viên cùng ngữ cảnh, quy ước và cổng chất lượng." },
        { title: "Ngành có quy định chặt", body: "Truy vết từ yêu cầu đến commit đáp ứng nhu cầu kiểm toán và tuân thủ." },
      ],
    },
    delivery: {
      title: "Bàn giao & cấp phép",
      body: "HAL-SDLC được cấp phép riêng cho tổ chức và triển khai trong hạ tầng của bạn. Điều khoản thương mại, gói hỗ trợ và nhịp cập nhật được xác định theo từng hợp đồng.",
      items: [
        "Phân phối riêng — bản phát hành có tag hoặc gói nén có checksum",
        "Hoạt động với Cursor và công cụ tương thích MCP",
        "Cài đặt, onboarding và hỗ trợ theo gói",
        "Tùy chỉnh mẫu, kỹ năng và persona review (tùy chọn)",
      ],
    },
    faq: {
      title: "Câu hỏi thường gặp",
      items: [
        { q: "HAL có thay thế lập trình viên không?", a: "Không. HAL loại bỏ mã lặp và chi phí phối hợp để lập trình viên dành thời gian cho phán đoán, kiến trúc và review. Con người phê duyệt mọi pull request." },
        { q: "Hỗ trợ ngôn ngữ và stack nào?", a: "HAL độc lập stack ở tầng lập kế hoạch và review, và có sẵn mẫu cho TypeScript, Python cùng các kiến trúc web và dịch vụ phổ biến. Stack khác được bổ sung qua mẫu và bản chưng cất." },
        { q: "Mã nguồn của chúng tôi đi đâu?", a: "Không đi đâu cả. HAL chạy trong môi trường của bạn và kết nối với nhà cung cấp mô hình bạn phê duyệt. Sản phẩm sinh ra nằm trong repository của bạn." },
        { q: "Bắt đầu thế nào?", a: "Một thí điểm ngắn trên hạng mục backlog thật: chúng tôi cài HAL, cùng lập kế hoạch và thực thi, rồi đo thời gian chu kỳ và chất lượng review so với đường cơ sở của bạn." },
      ],
    },
  },
  work: {
    title: "Dự án",
    subtitle: "Các giải pháp tiêu biểu chúng tôi đã thiết kế và bàn giao. Chi tiết được chia sẻ theo NDA khi cần.",
    items: [
      {
        slug: "enterprise-virtual-assistant",
        title: "Trợ lý ảo doanh nghiệp cho tập đoàn bán lẻ",
        client: "Bán lẻ & tiêu dùng",
        industry: "Bán lẻ",
        pillar: "ai-enterprise",
        summary: "Trợ lý ảo đa ngôn ngữ trả lời câu hỏi của khách hàng và nhân viên từ tri thức công ty, kết nối với hệ thống nội bộ.",
        challenge: "Đội hỗ trợ xử lý các câu hỏi lặp lại trên nhiều kênh trong khi chính sách và thông tin sản phẩm thay đổi hàng tuần. Chatbot cũ dựa trên luật và nhanh chóng lạc hậu.",
        solution: "Chúng tôi thiết kế trợ lý dựa trên truy xuất với thiết kế hội thoại theo thương hiệu, kết nối nguồn tri thức và API nội bộ, tích hợp đánh giá và chuyển tiếp cho nhân viên.",
        results: ["Câu trả lời nhất quán trên web và kênh nhắn tin", "Cập nhật tri thức không cần huấn luyện lại", "Chuyển tiếp rõ ràng cho nhân viên với đầy đủ ngữ cảnh"],
      },
      {
        slug: "voice-ai-companion",
        title: "Người bạn ảo giọng nói thời gian thực để luyện hội thoại",
        client: "Ứng dụng tiêu dùng",
        industry: "Giáo dục & tiêu dùng",
        pillar: "ai-robot",
        summary: "Ứng dụng đồng hành giọng nói sang giọng nói, nơi người học trò chuyện với nhân vật có tính cách, giọng nói và khuôn mặt động riêng — chính bộ não hội thoại chúng tôi mang vào robot giáo dục.",
        challenge: "Mang lại hội thoại giọng nói tự nhiên, độ trễ thấp với avatar biểu cảm khớp khẩu hình trên iOS, Android và web — đủ hấp dẫn để người học tiếp tục luyện tập.",
        solution: "Chúng tôi xây dựng pipeline đa phương thức — nhận dạng giọng nói, suy luận theo nhân vật có rào chắn, tổng hợp giọng nói chất lượng cao và video khớp khẩu hình — sau một trải nghiệm mobile-first để tạo và trò chuyện với nhân vật.",
        results: ["Phát hành đa nền tảng từ một mã nguồn", "Hội thoại nhất quán theo tính cách với giọng nói tùy chỉnh", "Cùng pipeline nay vận hành hội thoại và gia sư trên robot"],
      },
      {
        slug: "generative-film-pipeline",
        title: "Pipeline sinh ảnh & video cho concept phim",
        client: "Truyền thông & giải trí",
        industry: "Truyền thông",
        pillar: "ai-enterprise",
        summary: "Pipeline sản xuất biến kịch bản và prompt thành hình ảnh concept nhất quán và các đoạn video ngắn.",
        challenge: "Phát triển concept phim đòi hỏi nhiều vòng lặp hình ảnh và thử chuyển động vốn chậm và tốn kém khi làm theo cách truyền thống.",
        solution: "Chúng tôi xây dựng pipeline điều phối dùng các mô hình sinh ảnh và video tiên tiến với quản lý prompt, nhất quán phong cách và quy trình review cho đội sáng tạo.",
        results: ["Vòng lặp concept tính bằng giờ thay vì tuần", "Phong cách hình ảnh nhất quán giữa các cảnh", "Đội sáng tạo tập trung vào chỉ đạo, không phải công cụ"],
      },
      {
        slug: "geospatial-heritage-platform",
        title: "Nền tảng địa lý di sản toàn quốc",
        client: "Văn hóa & du lịch",
        industry: "Công & du lịch",
        pillar: "ai-enterprise",
        summary: "Danh bạ song ngữ dạng bản đồ với hơn 3.000 địa điểm văn hóa, làm giàu dữ liệu bằng AI và các trang tối ưu tìm kiếm.",
        challenge: "Thông tin địa điểm phân tán trên nhiều nguồn, không nhất quán và không có ở định dạng hiện đại, tìm kiếm được.",
        solution: "Chúng tôi xây dựng pipeline thu thập tự động và làm giàu bằng AI, bản đồ tương tác gom cụm, và hàng nghìn trang song ngữ tĩnh tối ưu cho tìm kiếm và di động.",
        results: ["3.000+ địa điểm được lập bản đồ và làm giàu", "Trang tĩnh nhanh, xếp hạng tốt cho tìm kiếm địa phương", "Nội dung song ngữ với khám phá theo tỉnh, tuyến và lễ hội"],
      },
      {
        slug: "ai-sdlc-adoption",
        title: "Engine AI SDLC tự xây dựng chính mình",
        client: "TechHala",
        industry: "Phần mềm",
        pillar: "ai-sdlc",
        summary: "Kỹ năng, agent và dịch vụ của HAL-SDLC được lập kế hoạch, xây dựng và review bởi chính HAL — bài kiểm tra mạnh nhất cho phương pháp.",
        challenge: "Chứng minh rằng lập kế hoạch bằng AI và thực thi đa agent có thể tạo ra phần mềm chất lượng production với truy vết, không chỉ là demo.",
        solution: "Mỗi năng lực mới — từ persona review đến API nội bộ — đều đi qua vòng lặp lập kế hoạch → thực thi → review → phát hành của HAL, với bài học tích lũy vào lớp tri thức.",
        results: ["Nền tảng tự khởi tạo với nhật ký quyết định đầy đủ", "Review độc lập cho mọi sản phẩm", "Phương pháp được kiểm chứng trước khi cung cấp cho khách hàng"],
      },
    ],
  },
  about: {
    title: "Về TechHala",
    subtitle: "Studio kỹ thuật AI xây dựng trí tuệ cho robot, đội ngũ phần mềm và doanh nghiệp.",
    mission: {
      title: "Sứ mệnh",
      body: "Biến AI thành một kỷ luật kỹ thuật đáng tin cậy — truy vết được, review được và vận hành thật — dù là dạy một em nhỏ, xây phần mềm hay phục vụ một tổ chức.",
    },
    values: [
      { title: "Truy vết mặc định", body: "Mọi quyết định của AI cần có lý do đọc được và hồ sơ kiểm toán được." },
      { title: "Con người kiểm soát", body: "Agent làm việc; con người quyết định. Chúng tôi thiết kế cổng phê duyệt, không tự động hóa mù quáng." },
      { title: "Vận hành thật hơn demo", body: "Chúng tôi đo mình bằng những gì chạy ổn định cho người dùng, không phải thứ đẹp trong video." },
      { title: "Học hỏi tích lũy", body: "Mỗi dự án đưa tri thức vào dự án tiếp theo — cho chúng tôi và cho khách hàng." },
    ],
    story: {
      title: "Câu chuyện",
      paragraphs: [
        "TechHala bắt đầu từ một trăn trở đơn giản: AI có thể viết mã, nhưng không ai giải thích được vì sao nó viết như vậy — hay đủ tin tưởng để phát hành. Chúng tôi bắt tay xây dựng vòng đời còn thiếu quanh AI: lập kế hoạch, kiểm chứng và vận hành.",
        "Công việc đó trở thành HAL-SDLC, engine vòng đời phát triển phần mềm bằng AI của chúng tôi, và định hình cách chúng tôi tiếp cận mọi bài toán — từ triển khai dịch vụ AI trong doanh nghiệp đến trao cho robot giáo dục một giọng nói biết lắng nghe, hiểu và dạy.",
        "Hôm nay chúng tôi hợp tác với các tổ chức tại Việt Nam và quốc tế để thiết kế, xây dựng và vận hành các hệ thống AI đứng vững trong thế giới thực.",
      ],
    },
    stats: [
      { value: "3", label: "lĩnh vực trọng tâm" },
      { value: "1", label: "nền tảng chủ lực" },
      { value: "VN + Toàn cầu", label: "khách hàng phục vụ" },
      { value: "100%", label: "bàn giao có con người phê duyệt" },
    ],
  },
  contact: {
    title: "Liên hệ TechHala",
    subtitle: "Tư vấn chọn robot, hỗ trợ đơn hàng, bảo hành hoặc trao đổi về giải pháp AI cho doanh nghiệp. Gọi hotline để được trả lời ngay, hoặc gửi form — chúng tôi phản hồi trong 1 ngày làm việc.",
    form: {
      name: "Họ tên",
      email: "Email hoặc số điện thoại",
      company: "Công ty / Trường học (không bắt buộc)",
      topic: "Tôi cần",
      topics: ["Tư vấn mua robot", "Hỗ trợ đơn hàng & bảo hành", "Mua cho trường học / trung tâm", "AI cho SDLC / HAL-SDLC", "AI cho doanh nghiệp / AIOps", "Khác"],
      message: "Nội dung (tuổi của con, nhu cầu, câu hỏi…)",
      submit: "Gửi tin nhắn",
      sending: "Đang gửi…",
      success: "Cảm ơn — chúng tôi đã nhận được tin nhắn và sẽ liên hệ sớm.",
      error: "Có lỗi xảy ra. Vui lòng gửi email trực tiếp cho chúng tôi.",
    },
    aside: {
      title: "Gọi hoặc ghé văn phòng",
      body: "Hotline và Zalo hoạt động 8:30 – 18:00 các ngày trong tuần. Bạn có thể đến trải nghiệm robot trực tiếp tại văn phòng.",
      hours: "Thứ 2 – Thứ 7 · 8:30 – 18:00",
      visit: "Xem bản đồ",
    },
  },
  footer: {
    tagline: "Robot AI học tiếng Anh cho học sinh và trợ lý AI cho gia đình Việt — do TechHala phát triển tại Hà Nội.",
    products: "Sản phẩm",
    solutions: "Giải pháp",
    company: "Công ty",
    contact: "Liên hệ",
    rights: "Bảo lưu mọi quyền.",
    trackOrder: "Tra cứu đơn hàng",
  },
};
